# =========================================================
# 08_Figure3_AEILD_BridgeAtlas_AtlasV2.R
# Patch3: robust grid viewport drawing for R/grid versions where grid.draw(vp=...) is unsupported
# RA-ILD atlas v2.2.x manuscript figure builder
#
# Purpose
#   Build Figure 3: an AE-ILD-centred bridge atlas using ONLY outputs already
#   generated by 03-06, plus the current dictionary metadata for policy filtering.
#
# What this script does NOT do
#   - It does not reuse any previous Figure 3 output tables.
#   - It does not recompute text-mining from abstracts.
#   - It does not use hit-matrix-derived term labels or counts for the main panels.
#   - It does not treat treatment or infection context as primary disease-state bridges.
#
# Figure panels
#   A. AE-ILD directional wording signals from 06 signed-effect summary.
#   B. Conservative primary A -> B -> AE-ILD bridge map from 04 ABC output.
#      Bridge B nodes are deliberately given extra vertical spread for readability.
#   C. AE-ILD-only bridge evidence layers from 04-06:
#      ABC triads, AE-ILD co-mention, and AE-ILD signed wording.
#
# Supplementary output
#   A treatment/infection context-layer AE-ILD signal plot, built separately.
#
# Interpretation
#   All signals are abstract-level literature signals. They are not causal
#   estimates, treatment-effect estimates, infection-trigger estimates, or
#   validated biomarkers.
# =========================================================

source(file.path(getwd(), "00_setup_AtlasV2.R"))
assert_atlas_v2_setup(require_dictionary = TRUE)
quiet_install(c("dplyr", "readr", "stringr", "tibble", "tidyr", "purrr", "ggplot2"))

RUN_NAME <- "08_Figure3_AEILD_BridgeAtlas_AtlasV2"
log_msg("=== START ", RUN_NAME, " ===")

# -------------------------
# 0) Parameters
# -------------------------
AE_OUTCOME <- "AE-ILD"
MAX_SIGNED_TERMS <- as.integer(Sys.getenv("RAILD_FIG3_SIGNED_TOP_N", unset = "12"))
MAX_BRIDGE_TRIADS <- as.integer(Sys.getenv("RAILD_FIG3_TRIADS_TOP_N", unset = "10"))
MAX_BRIDGE_EVIDENCE_TERMS <- as.integer(Sys.getenv("RAILD_FIG3_BRIDGE_EVIDENCE_TOP_N", unset = "12"))
MIN_SIGNED_ARTICLES <- as.integer(Sys.getenv("RAILD_FIG3_MIN_SIGNED_ARTICLES", unset = "1"))

# Increase this if the B bridge column is still visually cramped.
B_NODE_VERTICAL_SPREAD <- as.numeric(Sys.getenv("RAILD_FIG3_B_NODE_SPREAD", unset = "4.4"))
A_NODE_VERTICAL_SPREAD <- as.numeric(Sys.getenv("RAILD_FIG3_A_NODE_SPREAD", unset = "6.2"))

# Measurement/modality nodes are valuable for coverage/sensitivity but are not
# primary disease-state bridges.
MEASUREMENT_ABC_SUBROLES <- c("B_measurement_modality", "B_measurement_derived_imaging_feature")
MEASUREMENT_TERMS_HARD_EXCLUDE <- c("HRCT", "quantitative_CT", "VRS")

# -------------------------
# 1) Load current dictionary and define current policy terms
# -------------------------
dic <- load_atlas_dictionary(require_dictionary = TRUE)

as_bool <- function(x) {
  if (is.logical(x)) return(x)
  tolower(as.character(x)) %in% c("true", "t", "1", "yes", "y")
}

# Current dictionary metadata is the source of truth for display policy.
measurement_terms <- dic |>
  dplyr::mutate(
    abc_subrole = dplyr::coalesce(as.character(abc_subrole), ""),
    domain = dplyr::coalesce(as.character(domain), ""),
    concept_family = dplyr::coalesce(as.character(concept_family), "")
  ) |>
  dplyr::filter(
    abc_subrole %in% MEASUREMENT_ABC_SUBROLES |
      domain %in% c("imaging_modality", "measurement_derived_imaging_feature") |
      concept_family %in% c("measurement_modality", "measurement_derived_imaging_feature") |
      term %in% MEASUREMENT_TERMS_HARD_EXCLUDE
  ) |>
  dplyr::pull(term) |>
  unique()

allowed_A <- select_primary_A_terms(dic)
allowed_B <- setdiff(select_primary_B_terms(dic), measurement_terms)
allowed_C <- select_primary_C_terms(dic, primary_outcomes_only = TRUE)

# Explicit context separation.
allowed_A <- setdiff(allowed_A, c(treatment_context_terms(dic), infection_context_terms(dic), measurement_terms))
allowed_B <- setdiff(allowed_B, c(treatment_context_terms(dic), infection_context_terms(dic)))

if (!AE_OUTCOME %in% allowed_C) {
  stop("AE-ILD is not available as a current primary outcome in the dictionary.")
}

# -------------------------
# 2) Locate and read 03-06 outputs
# -------------------------
file_abc_main <- file.path(DIR_TABLE, sprintf("abc_rankings_primary_AEILD_main_filtered_%s__%s.csv", CORPUS_TAG, DIC_TAG))
file_abc_all  <- file.path(DIR_TABLE, sprintf("abc_rankings_primary_all_outcomes_%s__%s.csv", CORPUS_TAG, DIC_TAG))
file_signed   <- file.path(DIR_TABLE, sprintf("signed_effects_summary_primary_atlas_%s__%s.csv", CORPUS_TAG, DIC_TAG))
file_cooc     <- file.path(DIR_TABLE, sprintf("cooc_npmi_lift_primary_atlas_%s__%s.csv", CORPUS_TAG, DIC_TAG))

file_signed_treatment <- file.path(DIR_TABLE, sprintf("signed_effects_summary_treatment_context_%s__%s.csv", CORPUS_TAG, DIC_TAG))
file_signed_infection <- file.path(DIR_TABLE, sprintf("signed_effects_summary_infection_context_%s__%s.csv", CORPUS_TAG, DIC_TAG))
file_cooc_treatment   <- file.path(DIR_TABLE, sprintf("cooc_npmi_lift_treatment_context_%s__%s.csv", CORPUS_TAG, DIC_TAG))
file_cooc_infection   <- file.path(DIR_TABLE, sprintf("cooc_npmi_lift_infection_context_%s__%s.csv", CORPUS_TAG, DIC_TAG))

required <- c(file_abc_main, file_signed, file_cooc)
missing_required <- required[!file.exists(required)]
if (length(missing_required)) {
  stop("Missing required 03-06 output(s):\n", paste(missing_required, collapse = "\n"),
       "\nRun 03-06 before 08.")
}

abc_main_raw <- readr::read_csv(file_abc_main, show_col_types = FALSE)
abc_all_raw  <- if (file.exists(file_abc_all)) readr::read_csv(file_abc_all, show_col_types = FALSE) else tibble::tibble()
signed_raw   <- readr::read_csv(file_signed, show_col_types = FALSE)
cooc_raw     <- readr::read_csv(file_cooc, show_col_types = FALSE)

signed_treatment_raw <- if (file.exists(file_signed_treatment)) readr::read_csv(file_signed_treatment, show_col_types = FALSE) else tibble::tibble()
signed_infection_raw <- if (file.exists(file_signed_infection)) readr::read_csv(file_signed_infection, show_col_types = FALSE) else tibble::tibble()
cooc_treatment_raw   <- if (file.exists(file_cooc_treatment)) readr::read_csv(file_cooc_treatment, show_col_types = FALSE) else tibble::tibble()
cooc_infection_raw   <- if (file.exists(file_cooc_infection)) readr::read_csv(file_cooc_infection, show_col_types = FALSE) else tibble::tibble()

# -------------------------
# 3) Helper functions
# -------------------------
label_of <- function(term) {
  v <- dic$preferred_label[match(term, dic$term)]
  v <- ifelse(is.na(v) | !nzchar(v), term, v)
  as.character(v)
}

short_label <- function(x, max_chars = 34L) {
  x <- as.character(x)
  x <- gsub("Acute exacerbation of ILD", "AE-ILD", x)
  x <- gsub("anti-citrullinated protein antibody/rheumatoid factor", "ACPA/RF", x, ignore.case = TRUE)
  x <- gsub("anti-citrullinated protein antibody", "ACPA", x, ignore.case = TRUE)
  x <- gsub("rheumatoid factor", "RF", x, ignore.case = TRUE)
  x <- gsub("usual interstitial pneumonia", "UIP", x, ignore.case = TRUE)
  x <- gsub("nonspecific interstitial pneumonia", "NSIP", x, ignore.case = TRUE)
  x <- gsub("organising pneumonia", "organizing pneumonia", x, ignore.case = TRUE)
  x <- gsub("neutrophil cell", "neutrophil", x, ignore.case = TRUE)
  x <- gsub("macrophage cell", "macrophage", x, ignore.case = TRUE)
  too_long <- nchar(x) > max_chars
  x[too_long] <- paste0(substr(x[too_long], 1, max_chars - 1), "…")
  x
}

# More clinically readable display layer for primary terms.
term_layer_label <- function(role, domain, family, class) {
  txt <- paste(domain, family, class)
  dplyr::case_when(
    role == "A" & grepl("genetic|MUC5B|TERT|telomere", txt, ignore.case = TRUE) ~ "Genetic/host upstream",
    role == "A" ~ "Host/exposure/serology",
    role == "B" & grepl("radiographic|pathologic|pattern|imaging|fibrotic|bronchiectasis|reticulation|honeycombing|ILD_pattern", txt, ignore.case = TRUE) ~ "Imaging/pattern bridge",
    role == "B" & grepl("pulmonary_function|physiology|severity|CPI|GAP|PFT", txt, ignore.case = TRUE) ~ "Physiology/severity bridge",
    role == "B" ~ "Biomarker/pathway bridge",
    TRUE ~ "Primary atlas"
  )
}

to_num <- function(x) suppressWarnings(as.numeric(x))
to_int <- function(x) suppressWarnings(as.integer(x))

vertical_positions <- function(n, spread) {
  if (n <= 0) return(numeric())
  if (n == 1) return(0)
  seq(from = spread / 2, to = -spread / 2, length.out = n)
}

# -------------------------
# 4) Conservative current-dictionary AE-ILD ABC triads
# -------------------------
filter_current_ae_triads <- function(tab) {
  if (!nrow(tab)) return(tab)
  tab |>
    dplyr::filter(C == AE_OUTCOME) |>
    dplyr::filter(A %in% allowed_A, B %in% allowed_B) |>
    dplyr::filter(!(A %in% measurement_terms), !(B %in% measurement_terms)) |>
    dplyr::mutate(
      AB_n11 = to_int(AB_n11),
      BC_n11 = to_int(BC_n11),
      AC_n11 = to_int(AC_n11),
      support_hmean = to_num(support_hmean),
      score_q = to_num(score_q),
      A_label = short_label(label_of(A), 30),
      B_label = short_label(label_of(B), 30),
      C_label = AE_OUTCOME
    ) |>
    dplyr::arrange(dplyr::desc(score_q), dplyr::desc(support_hmean), dplyr::desc(AB_n11 + BC_n11), A, B)
}

triads_main <- filter_current_ae_triads(abc_main_raw)
fallback_used <- FALSE
if (!nrow(triads_main) && nrow(abc_all_raw)) {
  fallback_used <- TRUE
  triads_main <- filter_current_ae_triads(abc_all_raw) |>
    dplyr::filter(AB_n11 >= 1, BC_n11 >= 1)
}

triads_top <- triads_main |>
  dplyr::slice_head(n = min(MAX_BRIDGE_TRIADS, nrow(triads_main)))

excluded_from_abc <- abc_main_raw |>
  dplyr::filter(C == AE_OUTCOME) |>
  dplyr::mutate(exclusion_reason = dplyr::case_when(
    !(A %in% allowed_A) ~ "A_not_current_primary_upstream",
    B %in% measurement_terms ~ "B_measurement_or_modality_node",
    !(B %in% allowed_B) ~ "B_not_current_primary_bridge",
    TRUE ~ "retained"
  )) |>
  dplyr::filter(exclusion_reason != "retained")

# -------------------------
# 5) Panel A: AE-ILD signed wording, strictly C == AE-ILD
# -------------------------
signed_ae <- signed_raw |>
  dplyr::filter(C == AE_OUTCOME) |>
  dplyr::filter(A %in% c(allowed_A, allowed_B)) |>
  dplyr::filter(!(A %in% measurement_terms)) |>
  dplyr::mutate(
    articles = to_int(articles),
    balance = to_num(balance),
    balance_low = to_num(balance_low),
    balance_high = to_num(balance_high),
    term_label = short_label(ifelse(!is.na(A_preferred_label) & nzchar(A_preferred_label), A_preferred_label, label_of(A)), 30),
    display_layer = term_layer_label(A_abc_role, A_domain, A_concept_family, A_class),
    display_layer = factor(display_layer, levels = c(
      "Host/exposure/serology",
      "Genetic/host upstream",
      "Imaging/pattern bridge",
      "Physiology/severity bridge",
      "Biomarker/pathway bridge",
      "Primary atlas"
    ))
  ) |>
  dplyr::filter(articles >= MIN_SIGNED_ARTICLES) |>
  dplyr::arrange(dplyr::desc(articles), dplyr::desc(abs(balance)), A) |>
  dplyr::slice_head(n = MAX_SIGNED_TERMS)

# -------------------------
# 6) Panel B: bridge network data
# -------------------------
if (nrow(triads_top)) {
  edge_ab <- triads_top |>
    dplyr::group_by(from = A, to = B) |>
    dplyr::summarise(edge_type = "A-B", edge_weight = max(AB_n11, na.rm = TRUE), edge_score = max(score_q, na.rm = TRUE), .groups = "drop")
  edge_bc <- triads_top |>
    dplyr::group_by(from = B, to = C) |>
    dplyr::summarise(edge_type = "B-C", edge_weight = max(BC_n11, na.rm = TRUE), edge_score = max(score_q, na.rm = TRUE), .groups = "drop")
  edges <- dplyr::bind_rows(edge_ab, edge_bc)

  A_order <- triads_top |>
    dplyr::group_by(term = A) |>
    dplyr::summarise(score = max(score_q), support = sum(AB_n11), .groups = "drop") |>
    dplyr::arrange(dplyr::desc(score), dplyr::desc(support), term) |>
    dplyr::pull(term)
  B_order <- triads_top |>
    dplyr::group_by(term = B) |>
    dplyr::summarise(score = max(score_q), support = sum(BC_n11), .groups = "drop") |>
    dplyr::arrange(dplyr::desc(score), dplyr::desc(support), term) |>
    dplyr::pull(term)

  nodes_A <- tibble::tibble(term = A_order, label = short_label(label_of(A_order), 24), node_role = "A: upstream", x = 1, y = vertical_positions(length(A_order), A_NODE_VERTICAL_SPREAD))
  nodes_B <- tibble::tibble(term = B_order, label = short_label(label_of(B_order), 24), node_role = "B: bridge", x = 2, y = vertical_positions(length(B_order), B_NODE_VERTICAL_SPREAD))
  nodes_C <- tibble::tibble(term = AE_OUTCOME, label = "AE-ILD", node_role = "C: outcome", x = 3, y = 0)
  nodes <- dplyr::bind_rows(nodes_A, nodes_B, nodes_C) |>
    dplyr::left_join(
      dplyr::bind_rows(
        triads_top |> dplyr::group_by(term = A) |> dplyr::summarise(node_support = sum(AB_n11), .groups = "drop"),
        triads_top |> dplyr::group_by(term = B) |> dplyr::summarise(node_support = sum(BC_n11), .groups = "drop"),
        tibble::tibble(term = AE_OUTCOME, node_support = sum(triads_top$BC_n11, na.rm = TRUE))
      ) |>
        dplyr::group_by(term) |>
        dplyr::summarise(node_support = max(node_support, na.rm = TRUE), .groups = "drop"),
      by = "term"
    ) |>
    dplyr::mutate(node_support = ifelse(is.na(node_support), 1, node_support))

  edges_xy <- edges |>
    dplyr::left_join(nodes |> dplyr::select(from = term, x_from = x, y_from = y), by = "from") |>
    dplyr::left_join(nodes |> dplyr::select(to = term, x_to = x, y_to = y), by = "to")
} else {
  nodes <- tibble::tibble(term = character(), label = character(), node_role = character(), x = numeric(), y = numeric(), node_support = numeric())
  edges_xy <- tibble::tibble(from = character(), to = character(), edge_type = character(), edge_weight = numeric(), edge_score = numeric(), x_from = numeric(), y_from = numeric(), x_to = numeric(), y_to = numeric())
}

# -------------------------
# 7) Panel C: AE-ILD-only bridge evidence layers from 04-06
# -------------------------
cooc_ae_B <- cooc_raw |>
  dplyr::filter(C == AE_OUTCOME) |>
  dplyr::filter(A %in% allowed_B, !(A %in% measurement_terms)) |>
  dplyr::mutate(cooc_articles = to_int(n11)) |>
  dplyr::select(term = A, cooc_articles, cooc_npmi = npmi, cooc_lift = lift)

signed_ae_B <- signed_raw |>
  dplyr::filter(C == AE_OUTCOME) |>
  dplyr::filter(A %in% allowed_B, !(A %in% measurement_terms)) |>
  dplyr::mutate(signed_articles = to_int(articles), signed_balance = to_num(balance)) |>
  dplyr::select(term = A, signed_articles, signed_balance)

abc_ae_B <- triads_main |>
  dplyr::group_by(term = B) |>
  dplyr::summarise(
    abc_triads = dplyr::n(),
    abc_AB_support = sum(AB_n11, na.rm = TRUE),
    abc_BC_support = sum(BC_n11, na.rm = TRUE),
    abc_score_max = max(score_q, na.rm = TRUE),
    .groups = "drop"
  )

bridge_evidence <- tibble::tibble(term = unique(c(abc_ae_B$term, cooc_ae_B$term, signed_ae_B$term))) |>
  dplyr::filter(term %in% allowed_B, !(term %in% measurement_terms)) |>
  dplyr::left_join(abc_ae_B, by = "term") |>
  dplyr::left_join(cooc_ae_B, by = "term") |>
  dplyr::left_join(signed_ae_B, by = "term") |>
  dplyr::mutate(
    dplyr::across(c(abc_triads, abc_AB_support, abc_BC_support, cooc_articles, signed_articles), ~ ifelse(is.na(.x), 0, .x)),
    abc_score_max = ifelse(is.na(abc_score_max), 0, abc_score_max),
    cooc_npmi = ifelse(is.na(cooc_npmi), 0, cooc_npmi),
    signed_balance = ifelse(is.na(signed_balance), NA_real_, signed_balance),
    term_label = short_label(label_of(term), 28),
    rank_score = 2.5 * abc_triads + cooc_articles + signed_articles + 0.25 * abc_score_max
  ) |>
  dplyr::arrange(dplyr::desc(rank_score), dplyr::desc(cooc_articles), dplyr::desc(signed_articles), term) |>
  dplyr::slice_head(n = MAX_BRIDGE_EVIDENCE_TERMS)

bridge_evidence_long <- bridge_evidence |>
  dplyr::select(term, term_label, abc_triads, cooc_articles, signed_articles, rank_score) |>
  tidyr::pivot_longer(
    cols = c(abc_triads, cooc_articles, signed_articles),
    names_to = "evidence_type",
    values_to = "evidence_count"
  ) |>
  dplyr::mutate(
    evidence_type = dplyr::recode(
      evidence_type,
      abc_triads = "ABC bridge triads",
      cooc_articles = "AE-ILD co-mention articles",
      signed_articles = "AE-ILD signed-wording articles"
    ),
    evidence_type = factor(evidence_type, levels = c("ABC bridge triads", "AE-ILD co-mention articles", "AE-ILD signed-wording articles")),
    term_label = factor(term_label, levels = rev(bridge_evidence$term_label))
  )

# -------------------------
# 8) Supplementary context-layer AE-ILD data
# -------------------------
make_context_df <- function(cooc_df, signed_df, context_label) {
  co <- if (nrow(cooc_df)) {
    cooc_df |>
      dplyr::filter(C == AE_OUTCOME) |>
      dplyr::mutate(cooc_articles = to_int(n11)) |>
      dplyr::select(term = A, cooc_articles, cooc_npmi = npmi, cooc_lift = lift)
  } else tibble::tibble(term = character(), cooc_articles = integer(), cooc_npmi = numeric(), cooc_lift = numeric())

  si <- if (nrow(signed_df)) {
    signed_df |>
      dplyr::filter(C == AE_OUTCOME) |>
      dplyr::mutate(signed_articles = to_int(articles), signed_balance = to_num(balance)) |>
      dplyr::select(term = A, signed_articles, signed_balance)
  } else tibble::tibble(term = character(), signed_articles = integer(), signed_balance = numeric())

  tibble::tibble(term = unique(c(co$term, si$term))) |>
    dplyr::left_join(co, by = "term") |>
    dplyr::left_join(si, by = "term") |>
    dplyr::mutate(
      context_layer = context_label,
      cooc_articles = ifelse(is.na(cooc_articles), 0, cooc_articles),
      signed_articles = ifelse(is.na(signed_articles), 0, signed_articles),
      signed_balance = ifelse(is.na(signed_balance), NA_real_, signed_balance),
      term_label = short_label(label_of(term), 34)
    ) |>
    dplyr::filter(cooc_articles > 0 | signed_articles > 0)
}

context_terms <- dplyr::bind_rows(
  make_context_df(cooc_treatment_raw, signed_treatment_raw, "Treatment context"),
  make_context_df(cooc_infection_raw, signed_infection_raw, "Infection context")
) |>
  dplyr::arrange(context_layer, dplyr::desc(cooc_articles), dplyr::desc(signed_articles), term)

# -------------------------
# 9) Plots
# -------------------------
# Panel A
if (nrow(signed_ae)) {
  signed_ae <- signed_ae |>
    dplyr::mutate(term_label = factor(term_label, levels = rev(unique(term_label))))
  pA <- ggplot2::ggplot(signed_ae, ggplot2::aes(y = term_label)) +
    ggplot2::geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.3, color = "grey55") +
    ggplot2::geom_segment(ggplot2::aes(x = balance_low, xend = balance_high, yend = term_label), color = "grey65", linewidth = 0.5, na.rm = TRUE) +
    ggplot2::geom_point(ggplot2::aes(x = balance, size = articles, fill = balance), shape = 21, color = "grey25", alpha = 0.92) +
    ggplot2::scale_x_continuous(limits = c(-1, 1), breaks = c(-1, -0.5, 0, 0.5, 1)) +
    ggplot2::scale_size_continuous(range = c(2.0, 6.5)) +
    ggplot2::scale_fill_gradient2(limits = c(-1, 1), midpoint = 0, name = "Signed-effect\nbalance") +
    ggplot2::labs(
      title = "A. AE-ILD directional wording signals",
      subtitle = "Primary disease-state atlas terms only; C fixed to AE-ILD",
      x = "Balance of outcome-associated wording",
      y = NULL,
      size = "Articles"
    ) +
    ggplot2::theme_minimal(base_size = 10) +
    ggplot2::theme(
      plot.title = ggplot2::element_text(face = "bold", size = 11),
      plot.subtitle = ggplot2::element_text(size = 8.5),
      legend.position = "right",
      panel.grid.major.y = ggplot2::element_blank()
    )
} else {
  pA <- ggplot2::ggplot() +
    ggplot2::annotate("text", x = 0.5, y = 0.5, label = "No AE-ILD signed-effect rows available", size = 4) +
    ggplot2::theme_void() + ggplot2::labs(title = "A. AE-ILD directional wording signals")
}

# Panel B
if (nrow(nodes) && nrow(edges_xy)) {
  y_max <- max(abs(nodes$y), na.rm = TRUE) + 0.9
  pB <- ggplot2::ggplot() +
    ggplot2::geom_curve(
      data = edges_xy,
      ggplot2::aes(x = x_from, y = y_from, xend = x_to, yend = y_to, linewidth = edge_weight, alpha = edge_score),
      curvature = 0.06,
      arrow = grid::arrow(length = grid::unit(0.12, "cm")),
      color = "grey35"
    ) +
    ggplot2::geom_point(data = nodes, ggplot2::aes(x = x, y = y, size = node_support, shape = node_role), color = "grey20", fill = "white", stroke = 1.1) +
    ggplot2::geom_text(data = nodes |> dplyr::filter(node_role == "A: upstream"), ggplot2::aes(x = x - 0.05, y = y, label = label), hjust = 1, size = 3.0) +
    ggplot2::geom_text(data = nodes |> dplyr::filter(node_role == "B: bridge"), ggplot2::aes(x = x + 0.08, y = y, label = label), hjust = 0, size = 3.2, fontface = "bold") +
    ggplot2::geom_text(data = nodes |> dplyr::filter(node_role == "C: outcome"), ggplot2::aes(x = x + 0.08, y = y, label = label), hjust = 0, size = 3.4, fontface = "bold") +
    ggplot2::annotate("text", x = 1, y = y_max, label = "A\nupstream", fontface = "bold", size = 3.2, lineheight = 0.9) +
    ggplot2::annotate("text", x = 2, y = y_max, label = "B\nbridge", fontface = "bold", size = 3.2, lineheight = 0.9) +
    ggplot2::annotate("text", x = 3, y = y_max, label = "C\noutcome", fontface = "bold", size = 3.2, lineheight = 0.9) +
    ggplot2::scale_x_continuous(limits = c(0.42, 3.62), breaks = NULL) +
    ggplot2::scale_y_continuous(limits = c(-y_max, y_max), breaks = NULL) +
    ggplot2::scale_size_continuous(range = c(3.0, 8.0)) +
    ggplot2::scale_linewidth_continuous(range = c(0.35, 1.8)) +
    ggplot2::scale_alpha_continuous(range = c(0.35, 0.90)) +
    ggplot2::labs(
      title = "B. Conservative AE-ILD ABC bridge map",
      subtitle = "Current primary atlas only; treatment, infection and measurement nodes excluded",
      linewidth = "Edge support",
      alpha = "ABC score",
      size = "Node support",
      shape = NULL
    ) +
    ggplot2::theme_void(base_size = 10) +
    ggplot2::theme(
      plot.title = ggplot2::element_text(face = "bold", size = 11),
      plot.subtitle = ggplot2::element_text(size = 8.5),
      legend.position = "bottom",
      legend.box = "horizontal",
      plot.margin = grid::unit(c(6, 12, 6, 12), "pt")
    )
} else {
  pB <- ggplot2::ggplot() +
    ggplot2::annotate("text", x = 0.5, y = 0.5, label = "No conservative AE-ILD ABC bridges after current filtering", size = 4) +
    ggplot2::theme_void() + ggplot2::labs(title = "B. Conservative AE-ILD ABC bridge map")
}

# Panel C
if (nrow(bridge_evidence_long)) {
  pC <- ggplot2::ggplot(bridge_evidence_long |> dplyr::filter(evidence_count > 0), ggplot2::aes(x = evidence_type, y = term_label)) +
    ggplot2::geom_point(ggplot2::aes(size = evidence_count, fill = evidence_type), shape = 21, color = "grey25", alpha = 0.88) +
    ggplot2::scale_size_continuous(range = c(2.0, 8.5)) +
    ggplot2::labs(
      title = "C. AE-ILD-only bridge evidence layers",
      subtitle = "Counts are restricted to C = AE-ILD and derived from 04-06 tables",
      x = NULL,
      y = "Bridge B concept node",
      size = "Evidence count",
      fill = "Evidence layer"
    ) +
    ggplot2::theme_minimal(base_size = 10) +
    ggplot2::theme(
      plot.title = ggplot2::element_text(face = "bold", size = 11),
      plot.subtitle = ggplot2::element_text(size = 8.5),
      axis.text.x = ggplot2::element_text(angle = 12, hjust = 0.5),
      panel.grid.minor = ggplot2::element_blank(),
      legend.position = "right"
    )
} else {
  pC <- ggplot2::ggplot() +
    ggplot2::annotate("text", x = 0.5, y = 0.5, label = "No AE-ILD bridge evidence rows available", size = 4) +
    ggplot2::theme_void() + ggplot2::labs(title = "C. AE-ILD-only bridge evidence layers")
}

# Supplementary context figure
if (nrow(context_terms)) {
  context_terms_plot <- context_terms |>
    dplyr::mutate(term_label = factor(term_label, levels = rev(unique(term_label))))
  pS <- ggplot2::ggplot(context_terms_plot, ggplot2::aes(x = cooc_articles, y = term_label)) +
    ggplot2::geom_point(ggplot2::aes(size = pmax(cooc_articles, signed_articles), fill = signed_balance), shape = 21, color = "grey25", alpha = 0.9) +
    ggplot2::facet_grid(context_layer ~ ., scales = "free_y", space = "free_y") +
    ggplot2::scale_size_continuous(range = c(2.2, 7.5)) +
    ggplot2::scale_fill_gradient2(limits = c(-1, 1), midpoint = 0, na.value = "white") +
    ggplot2::labs(
      title = "Supplementary context-layer AE-ILD signals",
      subtitle = "Treatment and infection contexts are retained separately and not interpreted as primary disease-state bridges",
      x = "AE-ILD co-mentioned articles",
      y = NULL,
      size = "Context evidence",
      fill = "Signed-effect\nbalance"
    ) +
    ggplot2::theme_minimal(base_size = 10) +
    ggplot2::theme(
      plot.title = ggplot2::element_text(face = "bold", size = 13),
      strip.text.y = ggplot2::element_text(face = "bold", angle = 0),
      panel.grid.minor = ggplot2::element_blank(),
      legend.position = "right"
    )
} else {
  pS <- ggplot2::ggplot() +
    ggplot2::annotate("text", x = 0.5, y = 0.5, label = "No AE-ILD context-layer rows available", size = 4) +
    ggplot2::theme_void() + ggplot2::labs(title = "Supplementary context-layer AE-ILD signals")
}

# -------------------------
# 10) Save figures using base grid
# -------------------------
fig_pdf <- file.path(DIR_FIG2, sprintf("Figure3_AEILD_bridge_atlas_FINAL_%s__%s.pdf", CORPUS_TAG, DIC_TAG))
fig_png <- file.path(DIR_FIG2, sprintf("Figure3_AEILD_bridge_atlas_FINAL_%s__%s.png", CORPUS_TAG, DIC_TAG))
fig_supp_pdf <- file.path(DIR_FIG2, sprintf("Supplementary_AEILD_treatment_infection_context_%s__%s.pdf", CORPUS_TAG, DIC_TAG))
fig_supp_png <- file.path(DIR_FIG2, sprintf("Supplementary_AEILD_treatment_infection_context_%s__%s.png", CORPUS_TAG, DIC_TAG))

make_combined <- function() {
  # grid::grid.draw() does not accept a `vp=` argument in some R/grid versions.
  # Draw each ggplot grob after explicitly pushing the target viewport.
  draw_in_layout <- function(plot_obj, row, col) {
    grid::pushViewport(grid::viewport(layout.pos.row = row, layout.pos.col = col))
    grid::grid.draw(ggplot2::ggplotGrob(plot_obj))
    grid::popViewport()
  }

  grid::grid.newpage()
  grid::pushViewport(grid::viewport(layout = grid::grid.layout(
    nrow = 2, ncol = 2,
    heights = grid::unit(c(0.52, 0.48), "npc"),
    widths = grid::unit(c(0.43, 0.57), "npc")
  )))
  on.exit(grid::popViewport(), add = TRUE)

  draw_in_layout(pA, row = 1, col = 1)
  draw_in_layout(pB, row = 1, col = 2)
  draw_in_layout(pC, row = 2, col = 1:2)
}

save_main_figure_pdf <- function(path) {
  grDevices::pdf(path, width = 13.2, height = 9.4, onefile = TRUE)
  on.exit(grDevices::dev.off(), add = TRUE)
  make_combined()
}

save_main_figure_png <- function(path) {
  grDevices::png(path, width = 3960, height = 2820, res = 300)
  on.exit(grDevices::dev.off(), add = TRUE)
  make_combined()
}

save_gg_pdf <- function(plot_obj, path, width, height) {
  grDevices::pdf(path, width = width, height = height, onefile = TRUE)
  on.exit(grDevices::dev.off(), add = TRUE)
  print(plot_obj)
}

save_gg_png <- function(plot_obj, path, width, height, res = 300) {
  grDevices::png(path, width = width, height = height, res = res)
  on.exit(grDevices::dev.off(), add = TRUE)
  print(plot_obj)
}

save_main_figure_pdf(fig_pdf)
save_main_figure_png(fig_png)
save_gg_pdf(pS, fig_supp_pdf, width = 10.5, height = 5.6)
save_gg_png(pS, fig_supp_png, width = 3150, height = 1680, res = 300)

log_msg("WROTE:", fig_pdf)
log_msg("WROTE:", fig_png)
log_msg("WROTE:", fig_supp_pdf)
log_msg("WROTE:", fig_supp_png)

# -------------------------
# 11) Save tables and QC
# -------------------------
f_triads <- file.path(DIR_TABLE, sprintf("Figure3_AEILD_bridge_triads_FINAL_%s__%s.csv", CORPUS_TAG, DIC_TAG))
f_signed <- file.path(DIR_TABLE, sprintf("Figure3_AEILD_signed_top_terms_%s__%s.csv", CORPUS_TAG, DIC_TAG))
f_edges  <- file.path(DIR_TABLE, sprintf("Figure3_AEILD_bridge_edges_%s__%s.csv", CORPUS_TAG, DIC_TAG))
f_nodes  <- file.path(DIR_TABLE, sprintf("Figure3_AEILD_bridge_nodes_%s__%s.csv", CORPUS_TAG, DIC_TAG))
f_evid   <- file.path(DIR_TABLE, sprintf("Figure3_AEILD_bridge_evidence_AEILD_only_%s__%s.csv", CORPUS_TAG, DIC_TAG))
f_evid_long <- file.path(DIR_TABLE, sprintf("Figure3_AEILD_bridge_evidence_AEILD_only_LONG_%s__%s.csv", CORPUS_TAG, DIC_TAG))
f_excl   <- file.path(DIR_TABLE, sprintf("Figure3_AEILD_bridge_QC_excluded_current_dictionary_%s__%s.csv", CORPUS_TAG, DIC_TAG))
f_context <- file.path(DIR_TABLE, sprintf("Supplementary_AEILD_context_layer_terms_%s__%s.csv", CORPUS_TAG, DIC_TAG))
f_summary <- file.path(DIR_TABLE, sprintf("Figure3_AEILD_bridge_run_summary_%s__%s.csv", CORPUS_TAG, DIC_TAG))

run_summary <- tibble::tibble(
  metric = c(
    "AE_outcome",
    "source_tables",
    "allowed_A_terms_current_dictionary",
    "allowed_B_terms_current_dictionary_after_measurement_exclusion",
    "measurement_terms_excluded_from_B",
    "abc_main_rows_input",
    "abc_rows_excluded_by_current_dictionary",
    "abc_rows_retained_after_current_filtering",
    "abc_top_triads_displayed",
    "fallback_to_all_ABC_used",
    "signed_AE_rows_displayed",
    "bridge_evidence_terms_displayed",
    "context_AE_rows_saved",
    "B_node_vertical_spread",
    "figure_pdf",
    "figure_png",
    "supplement_pdf",
    "supplement_png"
  ),
  value = as.character(c(
    AE_OUTCOME,
    "04 ABC, 05 co-mention/NPMI, 06 signed-effect summaries",
    length(allowed_A),
    length(allowed_B),
    paste(measurement_terms, collapse = ";"),
    nrow(abc_main_raw),
    nrow(excluded_from_abc),
    nrow(triads_main),
    nrow(triads_top),
    fallback_used,
    nrow(signed_ae),
    nrow(bridge_evidence),
    nrow(context_terms),
    B_NODE_VERTICAL_SPREAD,
    fig_pdf,
    fig_png,
    fig_supp_pdf,
    fig_supp_png
  ))
)

write_csv2(triads_top, f_triads)
write_csv2(signed_ae, f_signed)
write_csv2(edges_xy, f_edges)
write_csv2(nodes, f_nodes)
write_csv2(bridge_evidence, f_evid)
write_csv2(bridge_evidence_long, f_evid_long)
write_csv2(excluded_from_abc, f_excl)
write_csv2(context_terms, f_context)
write_csv2(run_summary, f_summary)

log_msg("=== END ", RUN_NAME, " ===")
