# =========================================================
# 09_Figure4_ProgressionMortality_BridgeAtlas_AtlasV2.R
# RA-ILD atlas v2.2.x manuscript figure builder
#
# Purpose
#   Build Figure 4: a comparative bridge atlas for progression and mortality.
#   This script uses ONLY the outputs generated by 03-06, plus the current
#   dictionary metadata for policy filtering.
#
# Rationale
#   Figure 3 isolates AE-ILD, where evidence is sparse and the conservative
#   ABC bridge map concentrates around UIP/NSIP. Progression and mortality have
#   larger literature bases. Figure 4 therefore asks whether the same
#   outcome-preserving ABC framework identifies clinically interpretable bridge
#   structures for progression and mortality, without mixing in treatment,
#   infection, or measurement-context nodes.
#
# What this script does NOT do
#   - It does not use any previous Figure 4 or biomarker-atlas outputs.
#   - It does not recompute text-mining from abstracts.
#   - It does not treat treatment or infection context as primary disease-state bridges.
#   - It does not treat HRCT / quantitative CT / VRS as disease-state bridge nodes.
#
# Figure panels
#   A. Progression conservative bridge map.
#   B. Mortality conservative bridge map.
#   C. Shared versus outcome-facing disease-state bridge concepts.
#
# Supplementary output
#   A full top-triad ranking panel for progression and mortality.
#   The supplementary x-axis is displayed as log10(score + 1), with tick labels
#   on the original score scale, to avoid compression by high-mortality outliers.
#
# Interpretation
#   All signals are abstract-level literature signals. They are not causal
#   estimates, risk prediction models, treatment-effect estimates, or validated
#   prognostic biomarkers.
# =========================================================

source(file.path(getwd(), "00_setup_AtlasV2.R"))
assert_atlas_v2_setup(require_dictionary = TRUE)
quiet_install(c("dplyr", "readr", "stringr", "tibble", "tidyr", "purrr", "ggplot2"))

RUN_NAME <- "09_Figure4_ProgressionMortality_BridgeAtlas_AtlasV2"
log_msg("=== START ", RUN_NAME, " ===")

# -------------------------
# 0) Parameters
# -------------------------
TARGET_OUTCOMES <- c("progression", "mortality")
OUTCOME_LABELS <- c(progression = "Progression", mortality = "Mortality")

MAX_TRIADS_PER_OUTCOME <- as.integer(Sys.getenv("RAILD_FIG4_PM_TRIADS_TOP_N", unset = "18"))
MAX_A_NODES_PER_OUTCOME <- as.integer(Sys.getenv("RAILD_FIG4_PM_A_TOP_N", unset = "10"))
MAX_B_NODES_PER_OUTCOME <- as.integer(Sys.getenv("RAILD_FIG4_PM_B_TOP_N", unset = "10"))
MAX_BRIDGE_SUMMARY_TERMS <- as.integer(Sys.getenv("RAILD_FIG4_PM_BRIDGE_SUMMARY_TOP_N", unset = "16"))
MAX_SUPP_TRIADS_PER_OUTCOME <- as.integer(Sys.getenv("RAILD_FIG4_PM_SUPP_TRIADS_TOP_N", unset = "30"))

# Current main ABC support filters. If 04 has already filtered, this will not
# change those results; it simply safeguards against accidental all-table use.
MIN_AB_N11 <- as.integer(Sys.getenv("RAILD_FIG4_PM_MIN_AB_N11", unset = as.character(MIN_AB_N11_MAIN)))
MIN_BC_N11 <- as.integer(Sys.getenv("RAILD_FIG4_PM_MIN_BC_N11", unset = as.character(MIN_BC_N11_MAIN)))

A_NODE_VERTICAL_SPREAD <- as.numeric(Sys.getenv("RAILD_FIG4_PM_A_NODE_SPREAD", unset = "6.8"))
B_NODE_VERTICAL_SPREAD <- as.numeric(Sys.getenv("RAILD_FIG4_PM_B_NODE_SPREAD", unset = "6.8"))

# Measurement/modality nodes are retained elsewhere but not here.
MEASUREMENT_ABC_SUBROLES <- c("B_measurement_modality", "B_measurement_derived_imaging_feature")
MEASUREMENT_TERMS_HARD_EXCLUDE <- c("HRCT", "quantitative_CT", "VRS")

# -------------------------
# 1) Load dictionary and define current display policy
# -------------------------
dic <- load_atlas_dictionary(require_dictionary = TRUE)

as_bool_local <- function(x) {
  if (is.logical(x)) return(x)
  tolower(as.character(x)) %in% c("true", "t", "1", "yes", "y")
}

measurement_terms <- dic |>
  dplyr::mutate(
    abc_subrole = dplyr::coalesce(as.character(abc_subrole), ""),
    domain = dplyr::coalesce(as.character(domain), ""),
    concept_family = dplyr::coalesce(as.character(concept_family), "")
  ) |>
  dplyr::filter(
    abc_subrole %in% MEASUREMENT_ABC_SUBROLES |
      domain %in% c("imaging_modality", "measurement_derived_imaging_feature") |
      concept_family %in% c("measurement_modality", "measurement_derived_imaging_feature") |
      term %in% MEASUREMENT_TERMS_HARD_EXCLUDE
  ) |>
  dplyr::pull(term) |>
  unique()

allowed_A <- select_primary_A_terms(dic)
allowed_B <- setdiff(select_primary_B_terms(dic), measurement_terms)
allowed_C <- select_primary_C_terms(dic, primary_outcomes_only = TRUE)

allowed_A <- setdiff(allowed_A, c(treatment_context_terms(dic), infection_context_terms(dic), measurement_terms))
allowed_B <- setdiff(allowed_B, c(treatment_context_terms(dic), infection_context_terms(dic), measurement_terms))

missing_outcomes <- setdiff(TARGET_OUTCOMES, allowed_C)
if (length(missing_outcomes)) {
  stop("Target outcome(s) not available as current primary outcomes: ", paste(missing_outcomes, collapse = ", "))
}

# -------------------------
# 2) Locate and read 03-06 outputs
# -------------------------
file_abc_main <- file.path(DIR_TABLE, sprintf("abc_rankings_primary_main_filtered_%s__%s.csv", CORPUS_TAG, DIC_TAG))
file_abc_all  <- file.path(DIR_TABLE, sprintf("abc_rankings_primary_all_outcomes_%s__%s.csv", CORPUS_TAG, DIC_TAG))
file_signed   <- file.path(DIR_TABLE, sprintf("signed_effects_summary_primary_atlas_%s__%s.csv", CORPUS_TAG, DIC_TAG))
file_cooc     <- file.path(DIR_TABLE, sprintf("cooc_npmi_lift_primary_atlas_%s__%s.csv", CORPUS_TAG, DIC_TAG))

required_any_abc <- c(file_abc_main, file_abc_all)
if (!any(file.exists(required_any_abc))) {
  stop("Missing ABC output. Expected one of:\n", paste(required_any_abc, collapse = "\n"), "\nRun 04 before 09.")
}
if (!file.exists(file_cooc)) stop("Missing co-occurrence/NPMI output: ", file_cooc, "\nRun 05 before 09.")
if (!file.exists(file_signed)) stop("Missing signed-effect output: ", file_signed, "\nRun 06 before 09.")

abc_raw <- if (file.exists(file_abc_main)) readr::read_csv(file_abc_main, show_col_types = FALSE) else readr::read_csv(file_abc_all, show_col_types = FALSE)
abc_all_raw <- if (file.exists(file_abc_all)) readr::read_csv(file_abc_all, show_col_types = FALSE) else abc_raw
cooc_raw <- readr::read_csv(file_cooc, show_col_types = FALSE)
signed_raw <- readr::read_csv(file_signed, show_col_types = FALSE)

# -------------------------
# 3) Helpers
# -------------------------
label_of <- function(term) {
  v <- dic$preferred_label[match(term, dic$term)]
  v <- ifelse(is.na(v) | !nzchar(v), term, v)
  as.character(v)
}

short_label <- function(x, max_chars = 32L) {
  x <- as.character(x)
  x <- gsub("Acute exacerbation of ILD", "AE-ILD", x)
  x <- gsub("anti-citrullinated protein antibody/rheumatoid factor", "ACPA/RF", x, ignore.case = TRUE)
  x <- gsub("anti-citrullinated protein antibody", "ACPA", x, ignore.case = TRUE)
  x <- gsub("rheumatoid factor", "RF", x, ignore.case = TRUE)
  x <- gsub("usual interstitial pneumonia", "UIP", x, ignore.case = TRUE)
  x <- gsub("nonspecific interstitial pneumonia", "NSIP", x, ignore.case = TRUE)
  x <- gsub("diffusing capacity for carbon monoxide", "DLCO", x, ignore.case = TRUE)
  x <- gsub("forced vital capacity", "FVC", x, ignore.case = TRUE)
  x <- gsub("traction bronchiectasis", "traction bronchiectasis", x, ignore.case = TRUE)
  x <- gsub("neutrophil cell", "neutrophil", x, ignore.case = TRUE)
  x <- gsub("macrophage cell", "macrophage", x, ignore.case = TRUE)
  too_long <- nchar(x) > max_chars
  x[too_long] <- paste0(substr(x[too_long], 1, max_chars - 1), "…")
  x
}

to_num <- function(x) suppressWarnings(as.numeric(x))
to_int <- function(x) suppressWarnings(as.integer(x))

vertical_positions <- function(n, spread) {
  if (n <= 0) return(numeric())
  if (n == 1) return(0)
  seq(from = spread / 2, to = -spread / 2, length.out = n)
}

outcome_pretty <- function(x) {
  out <- OUTCOME_LABELS[x]
  out[is.na(out)] <- x[is.na(out)]
  as.character(out)
}

term_domain_label <- function(term) {
  row <- dic[dic$term == term, , drop = FALSE]
  if (!nrow(row)) return("Unknown")
  txt <- paste(row$abc_role, row$domain, row$concept_family, row$class, row$abc_subrole)
  dplyr::case_when(
    row$abc_role == "A" & grepl("genetic|MUC5B|TERT|telomere", txt, ignore.case = TRUE) ~ "Genetic/host",
    row$abc_role == "A" & grepl("serolog|ACPA|RF|ANA|Ro", txt, ignore.case = TRUE) ~ "Serology/upstream",
    row$abc_role == "A" ~ "Host/exposure",
    row$abc_role == "B" & grepl("radiographic|pathologic|pattern|imaging|fibrotic|bronchiectasis|reticulation|honeycombing|ILD_pattern|extent", txt, ignore.case = TRUE) ~ "Imaging/pattern",
    row$abc_role == "B" & grepl("pulmonary_function|physiology|severity|CPI|GAP|PFT|FVC|DLCO", txt, ignore.case = TRUE) ~ "Physiology/severity",
    row$abc_role == "B" ~ "Biomarker/pathway",
    TRUE ~ "Primary atlas"
  )
}

scale01 <- function(x, min_out = 0.4, max_out = 2.2) {
  x <- to_num(x)
  if (!length(x) || all(is.na(x))) return(rep(min_out, length(x)))
  rng <- range(x, na.rm = TRUE)
  if (!is.finite(rng[1]) || diff(rng) == 0) return(rep((min_out + max_out) / 2, length(x)))
  min_out + (x - rng[1]) / diff(rng) * (max_out - min_out)
}

# -------------------------
# 4) Current-policy ABC triads for progression/mortality
# -------------------------
filter_current_pm_triads <- function(tab) {
  if (!nrow(tab)) return(tab)
  tab |>
    dplyr::filter(C %in% TARGET_OUTCOMES) |>
    dplyr::filter(A %in% allowed_A, B %in% allowed_B) |>
    dplyr::filter(!(A %in% measurement_terms), !(B %in% measurement_terms)) |>
    dplyr::mutate(
      AB_n11 = to_int(AB_n11),
      BC_n11 = to_int(BC_n11),
      AC_n11 = to_int(AC_n11),
      support_hmean = to_num(support_hmean),
      score_q = to_num(score_q),
      AB_npmi = to_num(AB_npmi),
      BC_npmi = to_num(BC_npmi),
      A_label = short_label(label_of(A), 30),
      B_label = short_label(label_of(B), 30),
      outcome_label = outcome_pretty(C)
    ) |>
    dplyr::filter(AB_n11 >= MIN_AB_N11, BC_n11 >= MIN_BC_N11) |>
    dplyr::arrange(C, dplyr::desc(score_q), dplyr::desc(support_hmean), dplyr::desc(AB_n11 + BC_n11), A, B)
}

triads_current <- filter_current_pm_triads(abc_raw)

# If main-filter output is unexpectedly empty for an outcome, use all-outcome table
# but still apply current dictionary policy and support thresholds.
if (length(setdiff(TARGET_OUTCOMES, unique(triads_current$C))) && nrow(abc_all_raw)) {
  triads_all_current <- filter_current_pm_triads(abc_all_raw)
  missing <- setdiff(TARGET_OUTCOMES, unique(triads_current$C))
  triads_current <- dplyr::bind_rows(
    triads_current,
    triads_all_current |> dplyr::filter(C %in% missing)
  ) |>
    dplyr::distinct(A, B, C, .keep_all = TRUE) |>
    dplyr::arrange(C, dplyr::desc(score_q), dplyr::desc(support_hmean), dplyr::desc(AB_n11 + BC_n11), A, B)
}

if (!nrow(triads_current)) {
  stop("No progression/mortality primary ABC triads remained after current dictionary policy and support filters.")
}

# Select readable but data-driven triads per outcome.
select_triads_for_network <- function(tab, outcome) {
  d <- tab |> dplyr::filter(C == outcome) |>
    dplyr::arrange(dplyr::desc(score_q), dplyr::desc(support_hmean), dplyr::desc(AB_n11 + BC_n11), A, B)
  if (!nrow(d)) return(d)

  # First take a generous top set; then ensure the displayed graph is not visually overloaded.
  d_top <- d |> dplyr::slice_head(n = max(MAX_TRIADS_PER_OUTCOME * 2, MAX_TRIADS_PER_OUTCOME))

  top_A <- d_top |>
    dplyr::group_by(A) |>
    dplyr::summarise(max_score = max(score_q, na.rm = TRUE), support = sum(AB_n11, na.rm = TRUE), .groups = "drop") |>
    dplyr::arrange(dplyr::desc(max_score), dplyr::desc(support), A) |>
    dplyr::slice_head(n = MAX_A_NODES_PER_OUTCOME) |>
    dplyr::pull(A)
  top_B <- d_top |>
    dplyr::group_by(B) |>
    dplyr::summarise(max_score = max(score_q, na.rm = TRUE), support = sum(BC_n11, na.rm = TRUE), .groups = "drop") |>
    dplyr::arrange(dplyr::desc(max_score), dplyr::desc(support), B) |>
    dplyr::slice_head(n = MAX_B_NODES_PER_OUTCOME) |>
    dplyr::pull(B)

  d_top |>
    dplyr::filter(A %in% top_A, B %in% top_B) |>
    dplyr::slice_head(n = MAX_TRIADS_PER_OUTCOME)
}

triads_display <- purrr::map_dfr(TARGET_OUTCOMES, ~select_triads_for_network(triads_current, .x))

# -------------------------
# 5) Build bridge-map plot for one outcome
# -------------------------
make_bridge_plot <- function(outcome, panel_title) {
  tri <- triads_display |> dplyr::filter(C == outcome)
  if (!nrow(tri)) {
    return(ggplot2::ggplot() +
             ggplot2::annotate("text", x = 0, y = 0, label = paste("No displayable triads for", outcome_pretty(outcome))) +
             ggplot2::theme_void() +
             ggplot2::ggtitle(panel_title))
  }

  A_order <- tri |>
    dplyr::group_by(term = A) |>
    dplyr::summarise(max_score = max(score_q, na.rm = TRUE), support = sum(AB_n11, na.rm = TRUE), .groups = "drop") |>
    dplyr::arrange(dplyr::desc(max_score), dplyr::desc(support), term) |>
    dplyr::pull(term)

  B_order <- tri |>
    dplyr::group_by(term = B) |>
    dplyr::summarise(max_score = max(score_q, na.rm = TRUE), support = sum(BC_n11, na.rm = TRUE), .groups = "drop") |>
    dplyr::arrange(dplyr::desc(max_score), dplyr::desc(support), term) |>
    dplyr::pull(term)

  yA <- vertical_positions(length(A_order), A_NODE_VERTICAL_SPREAD)
  yB <- vertical_positions(length(B_order), B_NODE_VERTICAL_SPREAD)

  nodes_A <- tibble::tibble(term = A_order, role = "A", x = 0, y = yA)
  nodes_B <- tibble::tibble(term = B_order, role = "B", x = 1.22, y = yB)
  nodes_C <- tibble::tibble(term = outcome, role = "C", x = 2.46, y = 0)

  node_support_A <- tri |>
    dplyr::group_by(term = A) |>
    dplyr::summarise(node_support = sum(AB_n11, na.rm = TRUE), max_score = max(score_q, na.rm = TRUE), .groups = "drop")
  node_support_B <- tri |>
    dplyr::group_by(term = B) |>
    dplyr::summarise(node_support = sum(BC_n11, na.rm = TRUE), max_score = max(score_q, na.rm = TRUE), .groups = "drop")
  node_support_C <- tibble::tibble(term = outcome, node_support = max(tri$BC_n11, na.rm = TRUE), max_score = max(tri$score_q, na.rm = TRUE))

  nodes <- dplyr::bind_rows(nodes_A, nodes_B, nodes_C) |>
    dplyr::left_join(dplyr::bind_rows(node_support_A, node_support_B, node_support_C), by = "term") |>
    dplyr::mutate(
      label = dplyr::case_when(
        role == "C" ~ outcome_pretty(term),
        TRUE ~ short_label(label_of(term), 27)
      ),
      role_label = dplyr::case_when(
        role == "A" ~ "A: upstream",
        role == "B" ~ "B: disease-state bridge",
        role == "C" ~ "C: outcome",
        TRUE ~ role
      )
    )

  edge_ab <- tri |>
    dplyr::group_by(from = A, to = B) |>
    dplyr::summarise(edge_type = "A-B", edge_weight = max(AB_n11, na.rm = TRUE), edge_score = max(score_q, na.rm = TRUE), .groups = "drop")
  edge_bc <- tri |>
    dplyr::group_by(from = B, to = C) |>
    dplyr::summarise(edge_type = "B-C", edge_weight = max(BC_n11, na.rm = TRUE), edge_score = max(score_q, na.rm = TRUE), .groups = "drop")
  edges <- dplyr::bind_rows(edge_ab, edge_bc) |>
    dplyr::left_join(nodes |> dplyr::select(term, x, y), by = c("from" = "term")) |>
    dplyr::rename(x_from = x, y_from = y) |>
    dplyr::left_join(nodes |> dplyr::select(term, x, y), by = c("to" = "term")) |>
    dplyr::rename(x_to = x, y_to = y) |>
    dplyr::mutate(edge_width = scale01(edge_score, min_out = 0.35, max_out = 1.8))

  ggplot2::ggplot() +
    ggplot2::geom_segment(
      data = edges,
      ggplot2::aes(x = x_from, y = y_from, xend = x_to, yend = y_to, linewidth = edge_width, alpha = edge_weight),
      colour = "grey35", show.legend = FALSE
    ) +
    ggplot2::geom_point(
      data = nodes,
      ggplot2::aes(x = x, y = y, size = node_support, shape = role_label),
      fill = "white", colour = "grey10", stroke = 1.0
    ) +
    ggplot2::geom_text(
      data = nodes |> dplyr::filter(role == "A"),
      ggplot2::aes(x = x - 0.08, y = y, label = label),
      hjust = 1, size = 3.0, colour = "grey10"
    ) +
    ggplot2::geom_text(
      data = nodes |> dplyr::filter(role == "B"),
      ggplot2::aes(x = x + 0.07, y = y, label = label),
      hjust = 0, size = 3.15, fontface = "bold", colour = "grey10"
    ) +
    ggplot2::geom_text(
      data = nodes |> dplyr::filter(role == "C"),
      ggplot2::aes(x = x + 0.08, y = y, label = label),
      hjust = 0, size = 3.35, fontface = "bold", colour = "grey10"
    ) +
    ggplot2::annotate("text", x = 0, y = B_NODE_VERTICAL_SPREAD / 2 + 0.65, label = "A\nupstream", fontface = "bold", size = 3.0) +
    ggplot2::annotate("text", x = 1.22, y = B_NODE_VERTICAL_SPREAD / 2 + 0.65, label = "B\nbridge", fontface = "bold", size = 3.0) +
    ggplot2::annotate("text", x = 2.46, y = B_NODE_VERTICAL_SPREAD / 2 + 0.65, label = "C\noutcome", fontface = "bold", size = 3.0) +
    ggplot2::scale_shape_manual(values = c("A: upstream" = 21, "B: disease-state bridge" = 24, "C: outcome" = 22), name = NULL) +
    ggplot2::scale_size_continuous(range = c(2.5, 8), name = "Node\nsupport") +
    ggplot2::scale_alpha_continuous(range = c(0.25, 0.85), guide = "none") +
    ggplot2::scale_linewidth_continuous(range = c(0.25, 1.25), guide = "none") +
    ggplot2::coord_cartesian(xlim = c(-0.55, 2.95), ylim = c(-B_NODE_VERTICAL_SPREAD / 2 - 0.55, B_NODE_VERTICAL_SPREAD / 2 + 0.95), clip = "off") +
    ggplot2::labs(title = panel_title, subtitle = "Current primary atlas only; treatment, infection and measurement nodes excluded") +
    ggplot2::theme_void(base_size = 10) +
    ggplot2::theme(
      plot.title = ggplot2::element_text(face = "bold", size = 12, hjust = 0),
      plot.subtitle = ggplot2::element_text(size = 8.8, hjust = 0, colour = "grey35"),
      legend.position = "bottom",
      legend.box = "horizontal",
      plot.margin = ggplot2::margin(8, 14, 8, 22)
    )
}

pA <- make_bridge_plot("progression", "A. Progression bridge atlas")
pB <- make_bridge_plot("mortality", "B. Mortality bridge atlas")

# -------------------------
# 6) Panel C: shared vs outcome-facing B bridge concepts
# -------------------------
triad_bridge_summary <- triads_current |>
  dplyr::group_by(B, C) |>
  dplyr::summarise(
    abc_triads = dplyr::n(),
    max_score_q = max(score_q, na.rm = TRUE),
    sum_score_q = sum(score_q, na.rm = TRUE),
    max_BC_n11 = max(BC_n11, na.rm = TRUE),
    sum_AB_BC = sum(AB_n11 + BC_n11, na.rm = TRUE),
    .groups = "drop"
  )

cooc_BC <- cooc_raw |>
  dplyr::filter(A %in% allowed_B, C %in% TARGET_OUTCOMES) |>
  dplyr::filter(!(A %in% measurement_terms)) |>
  dplyr::transmute(B = A, C, cooc_articles = to_int(n11), cooc_npmi = to_num(npmi), cooc_lift = to_num(lift))

signed_BC <- signed_raw |>
  dplyr::filter(A %in% allowed_B, C %in% TARGET_OUTCOMES) |>
  dplyr::filter(!(A %in% measurement_terms)) |>
  dplyr::transmute(B = A, C, signed_articles = to_int(articles), balance = to_num(balance), balance_low = to_num(balance_low), balance_high = to_num(balance_high))

bridge_C <- dplyr::full_join(triad_bridge_summary, cooc_BC, by = c("B", "C")) |>
  dplyr::full_join(signed_BC, by = c("B", "C")) |>
  dplyr::filter(B %in% allowed_B, C %in% TARGET_OUTCOMES) |>
  dplyr::mutate(
    abc_triads = dplyr::coalesce(to_int(abc_triads), 0L),
    max_score_q = dplyr::coalesce(to_num(max_score_q), 0),
    sum_score_q = dplyr::coalesce(to_num(sum_score_q), 0),
    max_BC_n11 = dplyr::coalesce(to_int(max_BC_n11), 0L),
    cooc_articles = dplyr::coalesce(to_int(cooc_articles), 0L),
    signed_articles = dplyr::coalesce(to_int(signed_articles), 0L),
    balance = to_num(balance),
    evidence_articles = pmax(cooc_articles, max_BC_n11, signed_articles, na.rm = TRUE),
    display_label = short_label(label_of(B), 30)
  ) |>
  dplyr::filter(evidence_articles > 0 | abc_triads > 0)

bridge_class <- bridge_C |>
  dplyr::group_by(B) |>
  dplyr::summarise(
    outcomes_supported = sum(evidence_articles > 0 | abc_triads > 0),
    total_evidence = sum(evidence_articles, na.rm = TRUE),
    total_abc_triads = sum(abc_triads, na.rm = TRUE),
    progression_evidence = sum(evidence_articles[C == "progression"], na.rm = TRUE),
    mortality_evidence = sum(evidence_articles[C == "mortality"], na.rm = TRUE),
    .groups = "drop"
  ) |>
  dplyr::mutate(
    bridge_category = dplyr::case_when(
      progression_evidence > 0 & mortality_evidence > 0 ~ "Shared",
      progression_evidence > 0 & mortality_evidence == 0 ~ "Progression-facing",
      mortality_evidence > 0 & progression_evidence == 0 ~ "Mortality-facing",
      TRUE ~ "Other"
    )
  )

# balanced term selection for Panel C
select_bridge_terms <- bridge_class |>
  dplyr::filter(bridge_category %in% c("Shared", "Progression-facing", "Mortality-facing")) |>
  dplyr::group_by(bridge_category) |>
  dplyr::arrange(dplyr::desc(total_abc_triads > 0), dplyr::desc(total_evidence), dplyr::desc(total_abc_triads), B) |>
  dplyr::slice_head(n = ceiling(MAX_BRIDGE_SUMMARY_TERMS / 3)) |>
  dplyr::ungroup()

# If balanced selection is too sparse, add highest-evidence remaining bridge nodes.
if (nrow(select_bridge_terms) < MAX_BRIDGE_SUMMARY_TERMS) {
  add_terms <- bridge_class |>
    dplyr::filter(!B %in% select_bridge_terms$B) |>
    dplyr::arrange(dplyr::desc(total_abc_triads > 0), dplyr::desc(total_evidence), dplyr::desc(total_abc_triads), B) |>
    dplyr::slice_head(n = MAX_BRIDGE_SUMMARY_TERMS - nrow(select_bridge_terms))
  select_bridge_terms <- dplyr::bind_rows(select_bridge_terms, add_terms)
}

bridge_order <- select_bridge_terms |>
  dplyr::arrange(
    factor(bridge_category, levels = c("Shared", "Progression-facing", "Mortality-facing", "Other")),
    dplyr::desc(total_evidence),
    B
  ) |>
  dplyr::pull(B)

bridge_C_display <- bridge_C |>
  dplyr::filter(B %in% bridge_order) |>
  dplyr::left_join(bridge_class |> dplyr::select(B, bridge_category, total_evidence, total_abc_triads), by = "B") |>
  dplyr::mutate(
    C_label = factor(outcome_pretty(C), levels = c("Progression", "Mortality")),
    B_label = factor(short_label(label_of(B), 30), levels = rev(short_label(label_of(bridge_order), 30))),
    bridge_category = factor(bridge_category, levels = c("Shared", "Progression-facing", "Mortality-facing", "Other"))
  )

pC <- ggplot2::ggplot(bridge_C_display, ggplot2::aes(x = C_label, y = B_label)) +
  ggplot2::geom_point(ggplot2::aes(size = evidence_articles, fill = balance), shape = 21, colour = "grey30", stroke = 0.55) +
  ggplot2::facet_grid(bridge_category ~ ., scales = "free_y", space = "free_y") +
  ggplot2::scale_size_continuous(range = c(1.8, 9.5), name = "Bridge-outcome\nevidence count") +
  ggplot2::scale_fill_gradient2(low = "#b2182b", mid = "#f7f7f7", high = "#2166ac", midpoint = 0, na.value = "grey85", limits = c(-1, 1), name = "Signed-effect\nbalance") +
  ggplot2::labs(
    title = "C. Shared and outcome-facing bridge concepts",
    subtitle = "Bubble size uses bridge-outcome evidence from ABC, co-mention and signed-wording tables; grey indicates no direction-bearing wording",
    x = "Clinical worsening outcome",
    y = "B bridge concept node"
  ) +
  ggplot2::theme_minimal(base_size = 10) +
  ggplot2::theme(
    plot.title = ggplot2::element_text(face = "bold", size = 12),
    plot.subtitle = ggplot2::element_text(size = 8.7, colour = "grey35"),
    panel.grid.minor = ggplot2::element_blank(),
    panel.grid.major.x = ggplot2::element_line(colour = "grey88"),
    panel.grid.major.y = ggplot2::element_line(colour = "grey92"),
    strip.text.y = ggplot2::element_text(face = "bold", size = 8.8, angle = 0),
    axis.text.y = ggplot2::element_text(size = 8.5),
    axis.text.x = ggplot2::element_text(size = 9.5),
    legend.position = "right",
    plot.margin = ggplot2::margin(8, 10, 8, 10)
  )

# -------------------------
# 7) Supplementary top triad ranking panel
# -------------------------
supp_triads <- triads_current |>
  dplyr::group_by(C) |>
  dplyr::arrange(dplyr::desc(score_q), dplyr::desc(support_hmean), dplyr::desc(AB_n11 + BC_n11), A, B) |>
  dplyr::slice_head(n = MAX_SUPP_TRIADS_PER_OUTCOME) |>
  dplyr::ungroup() |>
  dplyr::mutate(
    triad_label = paste0(short_label(label_of(A), 22), " \u2192 ", short_label(label_of(B), 22)),
    C_label = factor(outcome_pretty(C), levels = c("Progression", "Mortality")),
    triad_label = stringr::str_wrap(triad_label, width = 36)
  )

# Need per-facet ordering without extra packages: build an ordered label with outcome prefix.
supp_triads <- supp_triads |>
  dplyr::group_by(C) |>
  dplyr::arrange(score_q, .by_group = TRUE) |>
  dplyr::mutate(triad_ordered = factor(paste(C, triad_label, sep = " | "), levels = paste(C, triad_label, sep = " | "))) |>
  dplyr::ungroup() |>
  dplyr::mutate(
    triad_axis_label = stringr::str_replace(as.character(triad_ordered), "^[^|]+ \\| ", ""),
    # Log-transformed display coordinate for the supplementary x-axis.
    # We use log10(score + 1), rather than scale_x_log10(), so the lollipop
    # stems can still start at zero. This prevents high-mortality outliers
    # from compressing the remaining progression/mortality triads.
    score_q_log10p1 = log10(dplyr::coalesce(to_num(score_q), 0) + 1)
  )

# Axis labels are shown on the original score scale, while the coordinate is log10(score + 1).
score_breaks_raw <- c(0, 1, 3, 10, 30, 100, 300, 1000, 3000)
max_score_supp <- max(supp_triads$score_q, na.rm = TRUE)
score_breaks_raw <- score_breaks_raw[score_breaks_raw <= max(max_score_supp * 1.05, 1)]
if (!0 %in% score_breaks_raw) score_breaks_raw <- c(0, score_breaks_raw)
score_breaks_plot <- log10(score_breaks_raw + 1)

pS <- ggplot2::ggplot(supp_triads, ggplot2::aes(x = score_q_log10p1, y = triad_ordered)) +
  ggplot2::geom_segment(ggplot2::aes(x = 0, xend = score_q_log10p1, yend = triad_ordered), colour = "grey75") +
  ggplot2::geom_point(ggplot2::aes(size = support_hmean, fill = BC_n11), shape = 21, colour = "grey25", stroke = 0.4) +
  ggplot2::facet_wrap(~C_label, scales = "free_y", ncol = 2) +
  ggplot2::scale_x_continuous(breaks = score_breaks_plot, labels = score_breaks_raw) +
  ggplot2::scale_y_discrete(labels = function(x) stringr::str_replace(x, "^[^|]+ \\| ", "")) +
  ggplot2::scale_size_continuous(range = c(1.8, 6.8), name = "Harmonic\nsupport") +
  ggplot2::scale_fill_gradient(low = "grey90", high = "grey20", name = "B-C\narticles") +
  ggplot2::labs(
    title = "Supplementary Figure. Top progression and mortality bridge triads",
    subtitle = "Current primary atlas only; treatment, infection and measurement context nodes excluded; x-axis shown on a log10(score + 1) scale",
    x = "Composite ABC bridge score (log10 scale; tick labels show original score)",
    y = "A \u2192 B bridge"
  ) +
  ggplot2::theme_minimal(base_size = 9.5) +
  ggplot2::theme(
    plot.title = ggplot2::element_text(face = "bold", size = 13),
    plot.subtitle = ggplot2::element_text(size = 9, colour = "grey35"),
    strip.text = ggplot2::element_text(face = "bold"),
    panel.grid.minor = ggplot2::element_blank(),
    axis.text.y = ggplot2::element_text(size = 6.7),
    legend.position = "right"
  )

# -------------------------
# 8) Write tables
# -------------------------
prefix <- sprintf("%s__%s", CORPUS_TAG, DIC_TAG)

table_triads_all <- file.path(DIR_TABLE, sprintf("Figure4_PM_bridge_triads_current_policy_%s.csv", prefix))
table_triads_display <- file.path(DIR_TABLE, sprintf("Figure4_PM_bridge_triads_display_%s.csv", prefix))
table_bridge_summary <- file.path(DIR_TABLE, sprintf("Figure4_PM_bridge_shared_outcome_facing_summary_%s.csv", prefix))
table_bridge_panelC <- file.path(DIR_TABLE, sprintf("Figure4_PM_bridge_panelC_display_%s.csv", prefix))
table_excluded <- file.path(DIR_TABLE, sprintf("Figure4_PM_QC_terms_excluded_by_current_dictionary_policy_%s.csv", prefix))
table_run <- file.path(DIR_TABLE, sprintf("Figure4_PM_bridge_run_summary_%s.csv", prefix))

excluded_pm <- abc_raw |>
  dplyr::filter(C %in% TARGET_OUTCOMES) |>
  dplyr::mutate(exclusion_reason = dplyr::case_when(
    !(A %in% allowed_A) ~ "A_not_current_primary_upstream",
    B %in% measurement_terms ~ "B_measurement_or_modality_node",
    !(B %in% allowed_B) ~ "B_not_current_primary_bridge",
    TRUE ~ "retained"
  )) |>
  dplyr::filter(exclusion_reason != "retained")

run_summary <- tibble::tibble(
  corpus_tag = CORPUS_TAG,
  dic_tag = DIC_TAG,
  target_outcomes = paste(TARGET_OUTCOMES, collapse = ";"),
  allowed_A_terms = length(allowed_A),
  allowed_B_terms = length(allowed_B),
  measurement_terms_excluded = length(measurement_terms),
  treatment_context_terms_excluded = length(treatment_context_terms(dic)),
  infection_context_terms_excluded = length(infection_context_terms(dic)),
  candidate_pm_triads_current_policy = nrow(triads_current),
  displayed_triads = nrow(triads_display),
  progression_displayed_triads = sum(triads_display$C == "progression"),
  mortality_displayed_triads = sum(triads_display$C == "mortality"),
  bridge_summary_terms_displayed = length(unique(bridge_C_display$B)),
  min_AB_n11 = MIN_AB_N11,
  min_BC_n11 = MIN_BC_N11,
  max_triads_per_outcome = MAX_TRIADS_PER_OUTCOME,
  interpretation = "Figure 4 uses current primary disease-state ABC bridges for progression and mortality; treatment, infection and measurement nodes are excluded from bridge claims."
)

write_csv2(triads_current, table_triads_all)
write_csv2(triads_display, table_triads_display)
write_csv2(bridge_class, table_bridge_summary)
write_csv2(bridge_C_display, table_bridge_panelC)
write_csv2(excluded_pm, table_excluded)
write_csv2(run_summary, table_run)

# -------------------------
# 9) Combined Figure 4 and supplementary figure
# -------------------------
fig_pdf <- file.path(DIR_FIG2, sprintf("Figure4_progression_mortality_bridge_atlas_FINAL_%s.pdf", prefix))
fig_png <- file.path(DIR_FIG2, sprintf("Figure4_progression_mortality_bridge_atlas_FINAL_%s.png", prefix))
fig_supp_pdf <- file.path(DIR_FIG2, sprintf("Supplementary_progression_mortality_full_bridge_triads_%s.pdf", prefix))
fig_supp_png <- file.path(DIR_FIG2, sprintf("Supplementary_progression_mortality_full_bridge_triads_%s.png", prefix))

# Robust manual layout. Avoid grid.draw(..., vp=...), which fails on some grid versions.
draw_in_viewport <- function(plot_obj, layout.pos.row, layout.pos.col) {
  grid::pushViewport(grid::viewport(layout.pos.row = layout.pos.row, layout.pos.col = layout.pos.col))
  grid::grid.draw(ggplot2::ggplotGrob(plot_obj))
  grid::popViewport()
}

make_combined <- function() {
  grid::grid.newpage()
  grid::pushViewport(grid::viewport(layout = grid::grid.layout(
    nrow = 2, ncol = 2,
    heights = grid::unit(c(0.50, 0.50), "npc"),
    widths = grid::unit(c(0.50, 0.50), "npc")
  )))
  draw_in_viewport(pA, 1, 1)
  draw_in_viewport(pB, 1, 2)
  draw_in_viewport(pC, 2, 1:2)
  grid::popViewport()
}

pdf(fig_pdf, width = 13.5, height = 9.8, onefile = TRUE)
make_combined()
dev.off()

png(fig_png, width = 4050, height = 2940, res = 300)
make_combined()
dev.off()

pdf(fig_supp_pdf, width = 12.2, height = 8.8, onefile = TRUE)
print(pS)
dev.off()

png(fig_supp_png, width = 3660, height = 2640, res = 300)
print(pS)
dev.off()

log_msg("WROTE:", fig_pdf)
log_msg("WROTE:", fig_png)
log_msg("WROTE:", fig_supp_pdf)
log_msg("WROTE:", fig_supp_png)
log_msg("=== DONE ", RUN_NAME, " ===")
