# =========================================================
# 10_Figure5_BiomarkerMolecularFreeAtlas_AtlasV2.R
# RA-ILD atlas v2.2.x manuscript figure builder
#
# Final Figure 5 concept
#   Figure 5: data-driven biomarker / molecular signal atlas overlaid on
#             disease-state bridge and outcome layers, drawn as a fully free
#             force-directed spider network. A separate integrated
#             shared/outcome-facing clinical summary can be generated by
#             11_Figure6_IntegratedSignalSummary_AtlasV2.R.
#
# Scientific purpose
#   Figures 3-4 show conservative A->B->C bridge atlases. Figure 5 is not a
#   second ABC map. Instead, it overlays biomarker / serological / molecular /
#   pathway signals onto selected primary disease-state B bridges and clinical
#   worsening outcomes. This is an exploratory literature-derived atlas, not a
#   causal diagram, validated biomarker panel, treatment-effect estimate, or
#   prediction model.
#
# Data-driven transparency
#   - The current dictionary metadata defines biomarker/molecular and B-bridge
#     scopes.
#   - Treatment, infection, comparator/context, measurement/modality and
#     non-scope disease-state terms are excluded from biomarker/molecular scope.
#   - Hit matrix counts determine all unique article-level co-mentions.
#   - Displayed nodes and text-summary terms are selected by prespecified
#     support/sharedness/signed-wording metrics only.
#   - No named biomarker, B node or result-derived term is hard-coded, anchored,
#     boosted or forced into display.
#
# Required prior outputs
#   00_setup_AtlasV2.R
#   02_BuildHitsMatrix_AtlasV2.R output: hits_matrix_*.csv
#   Optional but recommended: 06_SignedEffects_AtlasV2.R output for
#                             signed-effect balance on term-outcome edges.
#
# Outputs
#   Figure5_biomarker_molecular_free_atlas_FINAL_*.pdf/png
#   Supplementary_Figure5_full_biomarker_molecular_matrix_*.pdf/png
#   Figure5_free_nodes_*.csv
#   Figure5_free_edges_*.csv
#   Figure5_selection_rules_*.csv
#   Figure5_run_summary_*.csv
# =========================================================

source(file.path(getwd(), "00_setup_AtlasV2.R"))
assert_atlas_v2_setup(require_dictionary = TRUE)
quiet_install(c("dplyr", "readr", "stringr", "tibble", "tidyr", "purrr", "ggplot2", "grid", "ggrepel", "igraph"))

RUN_NAME <- "10_Figure5_BiomarkerMolecularFreeAtlas_AtlasV2"
log_msg("=== START ", RUN_NAME, " ===")

# -------------------------
# 0) Parameters
# -------------------------
OUTCOMES <- PRIMARY_OUTCOME_TERMS
OUTCOME_LABELS <- c("AE-ILD" = "AE-ILD", "progression" = "Progression", "mortality" = "Mortality")

MAX_BIOMARKER_TERMS <- as.integer(Sys.getenv("RAILD_FIG5_BIO_TOP_N", unset = "24"))
MAX_B_BRIDGE_TERMS <- as.integer(Sys.getenv("RAILD_FIG5_B_TOP_N", unset = "7"))
MIN_BIO_OUTCOME_COHIT <- as.integer(Sys.getenv("RAILD_FIG5_MIN_BIO_OUTCOME_COHIT", unset = "1"))
MIN_BIO_BRIDGE_COHIT <- as.integer(Sys.getenv("RAILD_FIG5_MIN_BIO_BRIDGE_COHIT", unset = "4"))
MIN_BRIDGE_OUTCOME_COHIT <- as.integer(Sys.getenv("RAILD_FIG5_MIN_BRIDGE_OUTCOME_COHIT", unset = "2"))
MAX_BIO_OUTCOME_EDGES <- as.integer(Sys.getenv("RAILD_FIG5_MAX_BIO_OUTCOME_EDGES", unset = "55"))
MAX_BIO_BRIDGE_EDGES <- as.integer(Sys.getenv("RAILD_FIG5_MAX_BIO_BRIDGE_EDGES", unset = "38"))
MAX_BRIDGE_OUTCOME_EDGES <- as.integer(Sys.getenv("RAILD_FIG5_MAX_BRIDGE_OUTCOME_EDGES", unset = "18"))
PANEL_B_TOP_N <- as.integer(Sys.getenv("RAILD_FIG5_PANEL_B_TOP_N", unset = "5"))
SUPP_MIN_COHIT <- as.integer(Sys.getenv("RAILD_FIG5_SUPP_MIN_COHIT", unset = "1"))

FIG_WIDTH <- as.numeric(Sys.getenv("RAILD_FIG5_WIDTH_IN", unset = "13.8"))
FIG_HEIGHT <- as.numeric(Sys.getenv("RAILD_FIG5_HEIGHT_IN", unset = "8.6"))
FIG_DPI <- as.integer(Sys.getenv("RAILD_FIG5_DPI", unset = "360"))
FREE_LAYOUT_SEED <- as.integer(Sys.getenv("RAILD_FIG5_FREE_LAYOUT_SEED", unset = "51961"))
FREE_LAYOUT_ITER <- as.integer(Sys.getenv("RAILD_FIG5_FREE_LAYOUT_ITER", unset = "2500"))
FREE_LAYOUT_EXPAND <- as.numeric(Sys.getenv("RAILD_FIG5_FREE_LAYOUT_EXPAND", unset = "3.15"))

MEASUREMENT_SUBROLES <- c("B_measurement_modality", "B_measurement_derived_imaging_feature")
MEASUREMENT_DOMAINS <- c("imaging_modality", "measurement_derived_imaging_feature")
MEASUREMENT_FAMILIES <- c("measurement_modality", "measurement_derived_imaging_feature")

# -------------------------
# 1) Helpers
# -------------------------
safe_chr <- function(x) {
  x <- as.character(x)
  x[is.na(x)] <- ""
  x
}

safe_num <- function(x, default = NA_real_) {
  y <- suppressWarnings(as.numeric(x))
  ifelse(is.na(y), default, y)
}

safe_int <- function(x, default = 0L) {
  y <- suppressWarnings(as.integer(x))
  ifelse(is.na(y), default, y)
}

read_optional_table <- function(prefix) {
  exact <- file.path(DIR_TABLE, sprintf("%s_%s__%s.csv", prefix, CORPUS_TAG, DIC_TAG))
  if (file.exists(exact)) {
    log_msg("Loaded table:", exact)
    return(readr::read_csv(exact, show_col_types = FALSE))
  }
  regex <- sprintf("^%s_.*__%s\\.csv$", prefix, DIC_TAG)
  alt <- find_latest_file(DIR_TABLE, regex)
  if (!is.na(alt) && file.exists(alt)) {
    log_msg("Loaded latest matching table:", alt)
    return(readr::read_csv(alt, show_col_types = FALSE))
  }
  log_msg("Optional table not found; using empty table for prefix:", prefix)
  tibble::tibble()
}

hit_col <- function(term) paste0("hit__", term)

get_vec <- function(df, term) {
  nm <- hit_col(term)
  if (!nm %in% names(df)) return(integer(nrow(df)))
  as.integer(ifelse(is.na(df[[nm]]), 0L, df[[nm]] > 0L))
}

cohit_count <- function(df, term1, term2) {
  x <- get_vec(df, term1)
  y <- get_vec(df, term2)
  as.integer(sum(x == 1L & y == 1L, na.rm = TRUE))
}

short_label <- function(x, max_chars = 34L) {
  x <- safe_chr(x)
  x <- gsub("anti-citrullinated protein antibody/rheumatoid factor", "ACPA/RF", x, ignore.case = TRUE)
  x <- gsub("anti-citrullinated protein antibody", "ACPA", x, ignore.case = TRUE)
  x <- gsub("rheumatoid factor", "RF", x, ignore.case = TRUE)
  x <- gsub("Surfactant protein", "SP", x, ignore.case = TRUE)
  x <- gsub("Neutrophil-to-lymphocyte ratio", "NLR", x, ignore.case = TRUE)
  x <- gsub("Krebs von den Lungen-6", "KL-6", x, ignore.case = TRUE)
  x <- gsub("Cytokine inflammation", "Cytokine/inflammation", x, ignore.case = TRUE)
  x <- gsub("extracellular matrix", "ECM", x, ignore.case = TRUE)
  x <- gsub("transforming growth factor", "TGF", x, ignore.case = TRUE)
  x <- gsub("matrix metalloproteinase", "MMP", x, ignore.case = TRUE)
  x <- gsub("SPP1 osteopontin", "SPP1/osteopontin", x, ignore.case = TRUE)
  too_long <- nchar(x) > max_chars
  x[too_long] <- paste0(substr(x[too_long], 1, max_chars - 1), "…")
  x
}

make_plot_label_map <- function(terms, summary_df, max_chars = 34L) {
  terms <- unique(safe_chr(terms))
  idx <- match(terms, safe_chr(summary_df$term))
  labs <- safe_chr(summary_df$display_label[idx])
  ids <- safe_chr(summary_df$term[idx])
  labs[!nzchar(labs)] <- ids[!nzchar(labs)]
  dup <- duplicated(labs) | duplicated(labs, fromLast = TRUE)
  labs[dup] <- paste0(labs[dup], " [", ids[dup], "]")
  labs <- short_label(labs, max_chars)
  labs <- make.unique(labs, sep = " ")
  tibble::tibble(term = terms, plot_label = labs)
}

label_repel <- function(data, mapping, size = 2.3, fontface = "plain", colour = "black", ...) {
  if (requireNamespace("ggrepel", quietly = TRUE)) {
    return(ggrepel::geom_text_repel(
      data = data, mapping = mapping, size = size, fontface = fontface, colour = colour,
      min.segment.length = 0, segment.size = 0.18, box.padding = 0.14, point.padding = 0.09,
      max.overlaps = Inf, ...
    ))
  }
  ggplot2::geom_text(data = data, mapping = mapping, size = size, fontface = fontface, colour = colour, ...)
}

is_measurement_node_vec <- function(abc_subrole, domain, concept_family) {
  safe_chr(abc_subrole) %in% MEASUREMENT_SUBROLES |
    safe_chr(domain) %in% MEASUREMENT_DOMAINS |
    safe_chr(concept_family) %in% MEASUREMENT_FAMILIES
}

assign_biomarker_group <- function(term, preferred_label, class, abc_role, abc_subrole, domain, concept_family, atlas_layer, node_level) {
  blob <- stringr::str_to_lower(paste(term, preferred_label, class, abc_role, abc_subrole, domain, concept_family, atlas_layer, node_level, sep = " | "))
  dplyr::case_when(
    stringr::str_detect(blob, "serolog|autoantibody|acpa|rheumatoid factor|anti_ro|anti-ro|ssa|ana|seropositive") ~ "Serological host phenotype",
    stringr::str_detect(blob, "aggregate.*pathway|pathway aggregate|aggregate_inflammation|aggregate_fibrosis|aggregate_oxidative|aggregate_checkpoint") ~ "Pathway aggregate/family",
    stringr::str_detect(blob, "oxidative|mda|malondialdehyde|isoprostane|8ohdg|gsh|hne|mpo|adma|endothelin") ~ "Oxidative/vascular/stress",
    stringr::str_detect(blob, "molecular_pathway|tgf|wnt|ecm|matrix|remodel|ctgf|ccn2|pai|galectin|periostin|osteopontin|spp1|profibrotic") ~ "Fibrosis/remodelling pathway",
    stringr::str_detect(blob, "cellular_process|immune_cell|stromal_cell|macrophage|neutrophil|fibroblast|myofibroblast|th17|b cell|b_cell") ~ "Cellular/inflammatory process",
    stringr::str_detect(blob, "chemokine|cytokine|interleukin|cxcl|ccl|il-|il[0-9]|gm.?csf|baff|pd1|pdl1|inflamm") ~ "Inflammatory/cytokine biomarker",
    stringr::str_detect(blob, "epithelial|surfactant|kl-?6|mmp|y.?kl|he4|cc16|scgb|injury|lung.*biomarker") ~ "Epithelial/fibrosis biomarker",
    stringr::str_detect(blob, "biomarker") ~ "Circulating biomarker",
    TRUE ~ "Biomarker/molecular candidate"
  )
}

is_biomarker_scope_vec <- function(term, preferred_label, class, abc_role, abc_subrole, domain, concept_family, atlas_layer, node_level) {
  dom <- safe_chr(domain)
  sub <- safe_chr(abc_subrole)
  fam <- safe_chr(concept_family)
  lay <- safe_chr(atlas_layer)
  role <- safe_chr(abc_role)
  node <- safe_chr(node_level)

  allowed_domains <- c("biomarker", "serological_host_factor", "molecular_pathway", "cellular_process")
  allowed_subroles <- c(
    "A_serological_phenotype",
    "B_circulating_or_tissue_biomarker",
    "B_cellular_process",
    "B_molecular_pathway"
  )
  disallowed_domains <- c(
    "treatment_context", "infection_safety_context", "context_population",
    "imaging_modality", "measurement_derived_imaging_feature",
    "radiology_feature", "radiographic_or_pathologic_pattern",
    "pulmonary_function", "severity_index", "airway_disease",
    "comorbidity_or_complication", "ILD_phenotype", "clinical_outcome",
    "RA_disease_activity", "modifier"
  )
  disallowed_subroles <- c(
    "A_treatment_context", "context_population_or_comparator",
    "B_measurement_modality", "B_measurement_derived_imaging_feature",
    "B_imaging_or_pattern", "B_imaging_extent_or_severity",
    "B_injury_or_pattern_descriptor", "B_physiology", "B_severity_index",
    "B_airway_disease", "B_ILD_phenotype_or_extent",
    "B_cardiopulmonary_burden", "A_comorbidity", "A_RA_clinical_context",
    "C_primary_worsening_outcome", "C_progression_component",
    "C_secondary_severe_outcome", "C_treatment_safety_context",
    "C_AE_ILD_synonym_or_component", "C_incident_ILD",
    "infection_safety_context", "infection_respiratory_context", "AE_ILD_infection_context",
    "modifier"
  )

  layer_ok <- lay %in% c("primary_atlas", "sensitivity", "exploratory")
  role_ok <- role %in% c("A", "B")
  metadata_scope <- dom %in% allowed_domains | sub %in% allowed_subroles
  family_scope <- stringr::str_detect(stringr::str_to_lower(fam), paste(c(
    "autoantibody", "serolog", "biomarker", "chemokine", "cytokine",
    "interleukin", "immune_cell", "stromal_cell", "profibrotic",
    "oxidative", "epithelial", "endothelial", "tgf", "matrix",
    "remodel", "checkpoint", "b_cell", "th17", "monocyte", "myeloid"
  ), collapse = "|"))
  aggregate_molecular <- node == "aggregate" & dom == "molecular_pathway"
  not_excluded <- !(dom %in% disallowed_domains | sub %in% disallowed_subroles)
  layer_ok & role_ok & not_excluded & (metadata_scope | family_scope | aggregate_molecular)
}

assign_bridge_group <- function(term, preferred_label, abc_subrole, domain, concept_family) {
  blob <- stringr::str_to_lower(paste(term, preferred_label, abc_subrole, domain, concept_family, sep = " | "))
  dplyr::case_when(
    stringr::str_detect(blob, "imaging|radiology|radiographic|pattern|uip|nsip|honeycomb|reticul|bronchiect|ground|dad|dip|op|organizing|cpfe|fibrosis_extent|extent") ~ "Imaging/pattern bridge",
    stringr::str_detect(blob, "physiology|pulmonary_function|fvc|dlco|pft|percent") ~ "Physiology bridge",
    stringr::str_detect(blob, "severity|index|gap|cpi") ~ "Severity index bridge",
    stringr::str_detect(blob, "pulmonary hypertension|cardiopulmonary|oxygen|respiratory failure") ~ "Cardiopulmonary bridge",
    TRUE ~ "Disease-state bridge"
  )
}

is_disease_bridge_scope_vec <- function(term, preferred_label, abc_role, abc_subrole, domain, concept_family, atlas_layer, include_primary, primary_atlas_eligible, node_level, is_measurement, is_biomarker_scope) {
  role <- safe_chr(abc_role)
  lay <- safe_chr(atlas_layer)
  dom <- safe_chr(domain)
  sub <- safe_chr(abc_subrole)
  node <- safe_chr(node_level)
  inc <- tolower(safe_chr(include_primary)) %in% c("true", "1", "yes")
  elig <- tolower(safe_chr(primary_atlas_eligible)) %in% c("true", "1", "yes")

  disallowed_subroles <- c(
    "A_treatment_context", "A_serological_phenotype", "A_RA_clinical_context", "A_comorbidity",
    "context_population_or_comparator", "B_measurement_modality", "B_measurement_derived_imaging_feature",
    "B_circulating_or_tissue_biomarker", "B_cellular_process", "B_molecular_pathway",
    "C_primary_worsening_outcome", "C_progression_component", "C_secondary_severe_outcome",
    "infection_safety_context", "infection_respiratory_context", "AE_ILD_infection_context", "modifier"
  )
  disallowed_domains <- c(
    "treatment_context", "infection_safety_context", "context_population",
    "imaging_modality", "measurement_derived_imaging_feature", "biomarker", "serological_host_factor",
    "molecular_pathway", "cellular_process", "clinical_outcome", "RA_disease_activity", "modifier"
  )
  layer_ok <- lay == "primary_atlas"
  role_ok <- role == "B"
  primary_ok <- inc | elig
  not_excluded <- !(sub %in% disallowed_subroles | dom %in% disallowed_domains | is_measurement | is_biomarker_scope)
  layer_ok & role_ok & primary_ok & not_excluded & node %in% c("specific", "aggregate", "")
}

signed_lookup <- function(signed06, terms, outcomes) {
  if (nrow(signed06) && all(c("A", "C", "articles", "balance") %in% names(signed06))) {
    signed06 |>
      dplyr::filter(A %in% terms, C %in% outcomes) |>
      dplyr::select(term = A, outcome = C, signed_articles = articles, signed_balance = balance) |>
      dplyr::mutate(signed_articles = safe_int(signed_articles, 0L), signed_balance = safe_num(signed_balance))
  } else {
    tibble::tibble(term = character(), outcome = character(), signed_articles = integer(), signed_balance = numeric())
  }
}

make_text_list <- function(df, n = 5L) {
  xs <- df |>
    dplyr::filter(!is.na(term), nzchar(safe_chr(term))) |>
    dplyr::slice_head(n = n) |>
    dplyr::mutate(txt = ifelse(
      max_outcome_cohit > 0,
      paste0(display_label, " (n=", max_outcome_cohit, ")"),
      display_label
    )) |>
    dplyr::pull(txt)
  if (!length(xs)) return("—")
  paste(xs, collapse = "; ")
}

# -------------------------
# 2) Load data
# -------------------------
dic <- load_atlas_dictionary(require_dictionary = TRUE)
for (col in c("preferred_label", "class", "abc_role", "abc_subrole", "domain", "concept_family", "atlas_layer", "node_level", "analysis_tier", "include_primary", "primary_atlas_eligible", "regex")) {
  if (!col %in% names(dic)) dic[[col]] <- ""
}
DF <- load_hit_matrix()
if (!"pmid" %in% names(DF)) stop("Hit matrix missing pmid column")
DF$pmid <- as.character(DF$pmid)

signed06 <- read_optional_table("signed_effects_summary_primary_atlas")

# -------------------------
# 3) Define scopes using current dictionary metadata
# -------------------------
dic_scope <- dic |>
  dplyr::mutate(
    is_measurement = is_measurement_node_vec(abc_subrole, domain, concept_family),
    biomarker_group = assign_biomarker_group(term, preferred_label, class, abc_role, abc_subrole, domain, concept_family, atlas_layer, node_level),
    is_biomarker_scope = is_biomarker_scope_vec(term, preferred_label, class, abc_role, abc_subrole, domain, concept_family, atlas_layer, node_level),
    bridge_group = assign_bridge_group(term, preferred_label, abc_subrole, domain, concept_family)
  ) |>
  dplyr::mutate(
    is_disease_bridge_scope = is_disease_bridge_scope_vec(term, preferred_label, abc_role, abc_subrole, domain, concept_family, atlas_layer, include_primary, primary_atlas_eligible, node_level, is_measurement, is_biomarker_scope),
    display_label = short_label(dplyr::coalesce(preferred_label, term), 36)
  )

scope_qc <- dic_scope |>
  dplyr::mutate(
    scope_flag = dplyr::case_when(
      is_biomarker_scope ~ "included: biomarker/molecular scope",
      is_disease_bridge_scope ~ "included: disease-state B bridge scope",
      atlas_layer == "treatment_context" ~ "excluded: treatment context",
      atlas_layer == "infection_context" ~ "excluded: infection context",
      atlas_layer == "context_only" ~ "excluded: context/comparator",
      is_measurement ~ "excluded: measurement/modality",
      TRUE ~ "excluded: outside Figure 5 scope"
    )
  ) |>
  dplyr::select(term, preferred_label, abc_role, abc_subrole, domain, concept_family, node_level, analysis_tier, atlas_layer, include_primary, primary_atlas_eligible, biomarker_group, bridge_group, is_biomarker_scope, is_disease_bridge_scope, scope_flag)
write_csv2(scope_qc, file.path(DIR_TABLE, sprintf("Figure5_scope_QC_all_terms_%s__%s.csv", CORPUS_TAG, DIC_TAG)))

biomarker_scope <- dic_scope |>
  dplyr::filter(is_biomarker_scope) |>
  dplyr::filter(hit_col(term) %in% names(DF)) |>
  dplyr::arrange(biomarker_group, term)
bridge_scope <- dic_scope |>
  dplyr::filter(is_disease_bridge_scope) |>
  dplyr::filter(hit_col(term) %in% names(DF)) |>
  dplyr::arrange(bridge_group, term)
write_csv2(biomarker_scope, file.path(DIR_TABLE, sprintf("Figure5_biomarker_molecular_scope_INCLUDED_%s__%s.csv", CORPUS_TAG, DIC_TAG)))
write_csv2(bridge_scope, file.path(DIR_TABLE, sprintf("Figure5_B_bridge_scope_INCLUDED_%s__%s.csv", CORPUS_TAG, DIC_TAG)))
if (!nrow(biomarker_scope)) stop("No biomarker/molecular scope terms selected. Check dictionary metadata.")
if (!nrow(bridge_scope)) stop("No disease-state B bridge scope terms selected. Check dictionary metadata.")

# -------------------------
# 4) Evidence matrices
# -------------------------
bio_outcome <- tidyr::expand_grid(term = biomarker_scope$term, outcome = OUTCOMES) |>
  dplyr::mutate(cohit_n = purrr::map2_int(term, outcome, ~cohit_count(DF, .x, .y))) |>
  dplyr::left_join(signed_lookup(signed06, biomarker_scope$term, OUTCOMES), by = c("term", "outcome")) |>
  dplyr::mutate(
    signed_articles = safe_int(signed_articles, 0L),
    signed_balance = safe_num(signed_balance),
    direction_available = signed_articles > 0 & !is.na(signed_balance)
  )

bridge_outcome <- tidyr::expand_grid(term = bridge_scope$term, outcome = OUTCOMES) |>
  dplyr::mutate(cohit_n = purrr::map2_int(term, outcome, ~cohit_count(DF, .x, .y))) |>
  dplyr::left_join(signed_lookup(signed06, bridge_scope$term, OUTCOMES), by = c("term", "outcome")) |>
  dplyr::mutate(
    signed_articles = safe_int(signed_articles, 0L),
    signed_balance = safe_num(signed_balance),
    direction_available = signed_articles > 0 & !is.na(signed_balance)
  )

bio_bridge <- tidyr::expand_grid(biomarker = biomarker_scope$term, bridge = bridge_scope$term) |>
  dplyr::mutate(cohit_n = purrr::map2_int(biomarker, bridge, ~cohit_count(DF, .x, .y)))

write_csv2(bio_outcome, file.path(DIR_TABLE, sprintf("Figure5_biomarker_outcome_edges_ALL_%s__%s.csv", CORPUS_TAG, DIC_TAG)))
write_csv2(bridge_outcome, file.path(DIR_TABLE, sprintf("Figure5_B_bridge_outcome_edges_ALL_%s__%s.csv", CORPUS_TAG, DIC_TAG)))
write_csv2(bio_bridge, file.path(DIR_TABLE, sprintf("Figure5_biomarker_B_edges_ALL_%s__%s.csv", CORPUS_TAG, DIC_TAG)))

# -------------------------
# 5) Data-driven node selection
# -------------------------
bio_summary <- biomarker_scope |>
  dplyr::select(term, preferred_label, display_label, group = biomarker_group, abc_role, abc_subrole, domain, concept_family, node_level, analysis_tier, atlas_layer) |>
  dplyr::left_join(
    bio_outcome |>
      dplyr::group_by(term) |>
      dplyr::summarise(
        total_outcome_cohit = sum(cohit_n, na.rm = TRUE),
        max_outcome_cohit = max(cohit_n, na.rm = TRUE),
        cohit_AE_ILD = sum(cohit_n[outcome == "AE-ILD"], na.rm = TRUE),
        cohit_progression = sum(cohit_n[outcome == "progression"], na.rm = TRUE),
        cohit_mortality = sum(cohit_n[outcome == "mortality"], na.rm = TRUE),
        outcomes_supported = sum(cohit_n >= MIN_BIO_OUTCOME_COHIT, na.rm = TRUE),
        signed_articles_total = sum(signed_articles, na.rm = TRUE),
        .groups = "drop"
      ),
    by = "term"
  ) |>
  dplyr::left_join(
    bio_bridge |>
      dplyr::group_by(term = biomarker) |>
      dplyr::summarise(
        total_bridge_cohit = sum(cohit_n, na.rm = TRUE),
        max_bridge_cohit = max(cohit_n, na.rm = TRUE),
        bridges_supported = sum(cohit_n >= MIN_BIO_BRIDGE_COHIT, na.rm = TRUE),
        .groups = "drop"
      ),
    by = "term"
  ) |>
  dplyr::mutate(
    dplyr::across(c(total_outcome_cohit, max_outcome_cohit, cohit_AE_ILD, cohit_progression, cohit_mortality, outcomes_supported, signed_articles_total, total_bridge_cohit, max_bridge_cohit, bridges_supported), ~safe_int(.x, 0L)),
    max_outcome = dplyr::case_when(
      max_outcome_cohit == 0 ~ "none",
      cohit_AE_ILD >= cohit_progression & cohit_AE_ILD >= cohit_mortality ~ "AE-ILD",
      cohit_progression >= cohit_AE_ILD & cohit_progression >= cohit_mortality ~ "progression",
      TRUE ~ "mortality"
    ),
    display_score = log1p(total_outcome_cohit) + 0.85 * outcomes_supported + 0.42 * log1p(total_bridge_cohit) + 0.20 * log1p(signed_articles_total)
  ) |>
  dplyr::arrange(dplyr::desc(total_outcome_cohit > 0 | total_bridge_cohit > 0), dplyr::desc(display_score), group, term)

selected_biomarkers <- bio_summary |>
  dplyr::filter(total_outcome_cohit > 0 | total_bridge_cohit >= MIN_BIO_BRIDGE_COHIT) |>
  dplyr::slice_head(n = MAX_BIOMARKER_TERMS) |>
  dplyr::pull(term)

bridge_summary <- bridge_scope |>
  dplyr::select(term, preferred_label, display_label, group = bridge_group, abc_role, abc_subrole, domain, concept_family, node_level, analysis_tier, atlas_layer) |>
  dplyr::left_join(
    bridge_outcome |>
      dplyr::group_by(term) |>
      dplyr::summarise(
        total_outcome_cohit = sum(cohit_n, na.rm = TRUE),
        max_outcome_cohit = max(cohit_n, na.rm = TRUE),
        outcomes_supported = sum(cohit_n >= MIN_BRIDGE_OUTCOME_COHIT, na.rm = TRUE),
        signed_articles_total = sum(signed_articles, na.rm = TRUE),
        .groups = "drop"
      ),
    by = "term"
  ) |>
  dplyr::left_join(
    bio_bridge |>
      dplyr::filter(biomarker %in% selected_biomarkers) |>
      dplyr::group_by(term = bridge) |>
      dplyr::summarise(
        total_biomarker_cohit = sum(cohit_n, na.rm = TRUE),
        max_biomarker_cohit = max(cohit_n, na.rm = TRUE),
        biomarkers_supported = sum(cohit_n >= MIN_BIO_BRIDGE_COHIT, na.rm = TRUE),
        .groups = "drop"
      ),
    by = "term"
  ) |>
  dplyr::mutate(
    dplyr::across(c(total_outcome_cohit, max_outcome_cohit, outcomes_supported, signed_articles_total, total_biomarker_cohit, max_biomarker_cohit, biomarkers_supported), ~safe_int(.x, 0L)),
    display_score = log1p(total_outcome_cohit) + 0.65 * outcomes_supported + 0.48 * log1p(total_biomarker_cohit) + 0.20 * log1p(signed_articles_total)
  ) |>
  dplyr::arrange(dplyr::desc(total_outcome_cohit > 0 & total_biomarker_cohit > 0), dplyr::desc(display_score), group, term)

selected_bridges <- bridge_summary |>
  dplyr::filter(total_outcome_cohit >= MIN_BRIDGE_OUTCOME_COHIT | total_biomarker_cohit >= MIN_BIO_BRIDGE_COHIT) |>
  dplyr::slice_head(n = MAX_B_BRIDGE_TERMS) |>
  dplyr::pull(term)

write_csv2(bio_summary, file.path(DIR_TABLE, sprintf("Figure5_biomarker_molecular_summary_%s__%s.csv", CORPUS_TAG, DIC_TAG)))
write_csv2(bridge_summary, file.path(DIR_TABLE, sprintf("Figure5_B_bridge_summary_%s__%s.csv", CORPUS_TAG, DIC_TAG)))

# -------------------------
# 6) Display edge sets
# -------------------------
bio_outcome_edges <- bio_outcome |>
  dplyr::filter(term %in% selected_biomarkers, cohit_n >= MIN_BIO_OUTCOME_COHIT) |>
  dplyr::arrange(dplyr::desc(cohit_n), term, outcome) |>
  dplyr::slice_head(n = MAX_BIO_OUTCOME_EDGES) |>
  dplyr::transmute(from = term, to = outcome, cohit_n, edge_type = "Biomarker-outcome", signed_balance = signed_balance, direction_available = direction_available)

bio_bridge_edges <- bio_bridge |>
  dplyr::filter(biomarker %in% selected_biomarkers, bridge %in% selected_bridges, cohit_n >= MIN_BIO_BRIDGE_COHIT) |>
  dplyr::arrange(dplyr::desc(cohit_n), biomarker, bridge) |>
  dplyr::slice_head(n = MAX_BIO_BRIDGE_EDGES) |>
  dplyr::transmute(from = biomarker, to = bridge, cohit_n, edge_type = "Biomarker-B bridge", signed_balance = NA_real_, direction_available = FALSE)

bridge_outcome_edges <- bridge_outcome |>
  dplyr::filter(term %in% selected_bridges, cohit_n >= MIN_BRIDGE_OUTCOME_COHIT) |>
  dplyr::arrange(dplyr::desc(cohit_n), term, outcome) |>
  dplyr::slice_head(n = MAX_BRIDGE_OUTCOME_EDGES) |>
  dplyr::transmute(from = term, to = outcome, cohit_n, edge_type = "B bridge-outcome", signed_balance = signed_balance, direction_available = direction_available)

edge_df <- dplyr::bind_rows(bio_outcome_edges, bio_bridge_edges, bridge_outcome_edges) |>
  dplyr::mutate(edge_balance_plot = ifelse(direction_available, signed_balance, NA_real_))

if (!nrow(edge_df)) stop("No Figure 5 edges after data-driven selection.")

# -------------------------
# 7) Node table and fully free force-directed layout
# -------------------------
bio_label_map <- make_plot_label_map(selected_biomarkers, bio_summary, max_chars = 31L)
bridge_label_map <- make_plot_label_map(selected_bridges, bridge_summary, max_chars = 28L)

bio_nodes <- bio_summary |>
  dplyr::filter(term %in% selected_biomarkers) |>
  dplyr::left_join(bio_label_map, by = "term") |>
  dplyr::mutate(node_id = term, node_type = "Biomarker/molecular concept", node_label = plot_label, node_support = total_outcome_cohit + total_bridge_cohit) |>
  dplyr::select(node_id, term, node_label, node_type, group, node_support, total_outcome_cohit, total_bridge_cohit, outcomes_supported, max_outcome, max_outcome_cohit, display_score, analysis_tier, atlas_layer, node_level)

bridge_nodes <- bridge_summary |>
  dplyr::filter(term %in% selected_bridges) |>
  dplyr::left_join(bridge_label_map, by = "term") |>
  dplyr::mutate(node_id = term, node_type = "Disease-state B bridge", node_label = plot_label, node_support = total_outcome_cohit + total_biomarker_cohit) |>
  dplyr::select(node_id, term, node_label, node_type, group, node_support, total_outcome_cohit, total_biomarker_cohit, outcomes_supported, display_score, analysis_tier, atlas_layer, node_level)

outcome_nodes <- tibble::tibble(
  node_id = OUTCOMES,
  term = OUTCOMES,
  node_label = unname(OUTCOME_LABELS[OUTCOMES]),
  node_type = "Clinical outcome",
  group = "Clinical outcome",
  node_support = purrr::map_int(OUTCOMES, ~sum(edge_df$cohit_n[edge_df$to == .x | edge_df$from == .x], na.rm = TRUE)),
  total_outcome_cohit = NA_integer_,
  total_bridge_cohit = NA_integer_,
  outcomes_supported = NA_integer_,
  max_outcome = NA_character_,
  max_outcome_cohit = NA_integer_,
  display_score = NA_real_,
  analysis_tier = "outcome",
  atlas_layer = "outcome",
  node_level = "outcome"
)

node_df <- dplyr::bind_rows(bio_nodes, bridge_nodes, outcome_nodes) |>
  dplyr::mutate(
    group = factor(group, levels = c(
      "Serological host phenotype",
      "Epithelial/fibrosis biomarker",
      "Inflammatory/cytokine biomarker",
      "Cellular/inflammatory process",
      "Fibrosis/remodelling pathway",
      "Oxidative/vascular/stress",
      "Pathway aggregate/family",
      "Biomarker/molecular candidate",
      "Circulating biomarker",
      "Imaging/pattern bridge",
      "Physiology bridge",
      "Severity index bridge",
      "Cardiopulmonary bridge",
      "Disease-state bridge",
      "Clinical outcome"
    ))
  )

# Fully free layout:
#   The displayed node set is laid out by a deterministic Fruchterman-Reingold
#   algorithm using article-level co-mention weights. Outcomes are not fixed and
#   no named terms are manually positioned. Edge classes are weighted modestly
#   differently for layout stability, but the transformation is prespecified and
#   independent of node names.
used_nodes <- unique(c(edge_df$from, edge_df$to))
node_plot <- node_df |>
  dplyr::filter(node_id %in% used_nodes) |>
  dplyr::mutate(node_id = as.character(node_id))

edge_plot_base <- edge_df |>
  dplyr::filter(from %in% node_plot$node_id, to %in% node_plot$node_id) |>
  dplyr::mutate(
    layout_weight = log1p(cohit_n) * dplyr::case_when(
      edge_type == "Biomarker-outcome" ~ 1.00,
      edge_type == "Biomarker-B bridge" ~ 0.78,
      edge_type == "B bridge-outcome" ~ 0.62,
      TRUE ~ 0.75
    )
  )

if (!nrow(edge_plot_base)) stop("No Figure 5 edges available for free-layout plotting.")

set.seed(FREE_LAYOUT_SEED)
g_free <- igraph::graph_from_data_frame(
  d = edge_plot_base |> dplyr::select(from, to, layout_weight),
  directed = FALSE,
  vertices = node_plot |> dplyr::select(name = node_id)
)
coords <- igraph::layout_with_fr(
  g_free,
  weights = igraph::E(g_free)$layout_weight,
  niter = FREE_LAYOUT_ITER,
  grid = "nogrid"
)
coords <- as.data.frame(coords)
names(coords) <- c("x_raw", "y_raw")
coords$node_id <- igraph::V(g_free)$name

rescale_center <- function(v) {
  v <- as.numeric(v)
  rng <- range(v, na.rm = TRUE)
  if (!is.finite(rng[1]) || !is.finite(rng[2]) || diff(rng) == 0) return(rep(0, length(v)))
  ((v - mean(rng)) / diff(rng)) * 2
}

layout_free <- node_plot |>
  dplyr::left_join(coords, by = "node_id") |>
  dplyr::mutate(
    x = rescale_center(x_raw) * FREE_LAYOUT_EXPAND,
    y = rescale_center(y_raw) * FREE_LAYOUT_EXPAND,
    # Put the outcome labels slightly in front visually without changing layout.
    label_size = dplyr::case_when(
      node_type == "Clinical outcome" ~ 3.20,
      node_type == "Disease-state B bridge" ~ 2.65,
      TRUE ~ 2.05
    )
  )

make_edge_layout <- function(edges, layout_df) {
  edges |>
    dplyr::left_join(layout_df |> dplyr::select(node_id, x, y), by = c("from" = "node_id")) |>
    dplyr::rename(x1 = x, y1 = y) |>
    dplyr::left_join(layout_df |> dplyr::select(node_id, x, y), by = c("to" = "node_id")) |>
    dplyr::rename(x2 = x, y2 = y)
}
edge_free <- make_edge_layout(edge_plot_base, layout_free)

write_csv2(node_df, file.path(DIR_TABLE, sprintf("Figure5_free_nodes_%s__%s.csv", CORPUS_TAG, DIC_TAG)))
write_csv2(edge_df, file.path(DIR_TABLE, sprintf("Figure5_free_edges_%s__%s.csv", CORPUS_TAG, DIC_TAG)))
write_csv2(layout_free, file.path(DIR_TABLE, sprintf("Figure5_free_layout_%s__%s.csv", CORPUS_TAG, DIC_TAG)))
# -------------------------

# 9) Supplementary full matrix
# -------------------------
supp_matrix <- bio_outcome |>
  dplyr::left_join(biomarker_scope |> dplyr::select(term, preferred_label, display_label, group = biomarker_group, analysis_tier, node_level), by = "term") |>
  dplyr::filter(cohit_n >= SUPP_MIN_COHIT) |>
  dplyr::mutate(
    outcome_label = factor(unname(OUTCOME_LABELS[outcome]), levels = unname(OUTCOME_LABELS[OUTCOMES])),
    display_label = short_label(display_label, 32),
    fill_value = ifelse(direction_available, signed_balance, NA_real_),
    display_label_unique = make.unique(display_label, sep = " ")
  )

if (nrow(supp_matrix)) {
  supp_levels <- supp_matrix |>
    dplyr::group_by(term, display_label_unique) |>
    dplyr::summarise(total = sum(cohit_n, na.rm = TRUE), group = dplyr::first(group), .groups = "drop") |>
    dplyr::arrange(group, dplyr::desc(total), display_label_unique) |>
    dplyr::pull(display_label_unique)
  supp_matrix <- supp_matrix |>
    dplyr::mutate(display_label_unique = factor(display_label_unique, levels = rev(unique(supp_levels))))
}
write_csv2(supp_matrix, file.path(DIR_TABLE, sprintf("Supplementary_Figure5_full_biomarker_molecular_matrix_data_%s__%s.csv", CORPUS_TAG, DIC_TAG)))

# -------------------------
# 10) Plotting
# -------------------------
base_theme_void <- ggplot2::theme_void(base_size = 10) +
  ggplot2::theme(
    plot.title = ggplot2::element_text(face = "bold", size = 13.5),
    plot.subtitle = ggplot2::element_text(size = 8.7),
    legend.title = ggplot2::element_text(size = 7.4, face = "bold"),
    legend.text = ggplot2::element_text(size = 6.35),
    legend.key.height = grid::unit(0.33, "lines"),
    legend.key.width = grid::unit(0.92, "lines"),
    legend.spacing.y = grid::unit(0.08, "lines"),
    legend.box = "vertical",
    legend.box.just = "left",
    legend.box.margin = grid::unit(c(0, 0, 0, 2), "pt"),
    plot.margin = grid::unit(c(8, 8, 8, 8), "pt")
  )

node_shapes <- c("Biomarker/molecular concept" = 21, "Disease-state B bridge" = 24, "Clinical outcome" = 22)
node_fill_values <- c(
  "Serological host phenotype" = "#E78AC3",
  "Epithelial/fibrosis biomarker" = "#D9A441",
  "Inflammatory/cytokine biomarker" = "#80CDC1",
  "Cellular/inflammatory process" = "#7FC97F",
  "Fibrosis/remodelling pathway" = "#4DB6AC",
  "Oxidative/vascular/stress" = "#67A9CF",
  "Pathway aggregate/family" = "#8E63CE",
  "Biomarker/molecular candidate" = "#BDBDBD",
  "Circulating biomarker" = "#D9A441",
  "Imaging/pattern bridge" = "#66C2A5",
  "Physiology bridge" = "#B276D2",
  "Severity index bridge" = "#FDAE61",
  "Cardiopulmonary bridge" = "#9ECAE1",
  "Disease-state bridge" = "#A6D854",
  "Clinical outcome" = "#F781BF"
)

# Compact legend labels for manuscript-size output. These labels affect only
# the legend; the node colours and data-driven grouping are unchanged.
node_group_legend_labels <- c(
  "Serological host phenotype" = "Serology",
  "Epithelial/fibrosis biomarker" = "Epithelial/fibrosis biomarker",
  "Inflammatory/cytokine biomarker" = "Inflammatory/cytokine",
  "Cellular/inflammatory process" = "Cellular process",
  "Fibrosis/remodelling pathway" = "Fibrosis/remodelling",
  "Oxidative/vascular/stress" = "Oxidative/vascular",
  "Pathway aggregate/family" = "Pathway aggregate",
  "Biomarker/molecular candidate" = "Biomarker/molecular candidate",
  "Circulating biomarker" = "Circulating biomarker",
  "Imaging/pattern bridge" = "Imaging/pattern bridge",
  "Physiology bridge" = "Physiology bridge",
  "Severity index bridge" = "Severity index bridge",
  "Cardiopulmonary bridge" = "Cardiopulmonary bridge",
  "Disease-state bridge" = "Disease-state bridge",
  "Clinical outcome" = "Clinical outcome"
)

# Active concept groups in this particular figure.
# Explicit breaks and override fills are used so the legend keys show the
# same colours as the plotted nodes, instead of default grey keys.
active_concept_groups <- intersect(names(node_fill_values), unique(layout_free$group))
active_concept_group_labels <- node_group_legend_labels[active_concept_groups]
active_concept_group_fills <- node_fill_values[active_concept_groups]

edge_bo <- edge_free |> dplyr::filter(edge_type == "Biomarker-outcome")
edge_bb <- edge_free |> dplyr::filter(edge_type == "Biomarker-B bridge")
edge_bc <- edge_free |> dplyr::filter(edge_type == "B bridge-outcome")

pA <- ggplot2::ggplot() +
  # background B-outcome architecture, kept light to avoid repeating Figures 3-4
  ggplot2::geom_curve(
    data = edge_bc,
    ggplot2::aes(x = x1, y = y1, xend = x2, yend = y2, linewidth = cohit_n),
    curvature = 0.10, colour = "grey78", alpha = 0.42, lineend = "round"
  ) +
  # biomarker-B co-mention layer
  ggplot2::geom_curve(
    data = edge_bb,
    ggplot2::aes(x = x1, y = y1, xend = x2, yend = y2, linewidth = cohit_n),
    curvature = -0.08, colour = "grey58", alpha = 0.30, linetype = "dotted", lineend = "round"
  ) +
  # biomarker-outcome signal layer
  ggplot2::geom_curve(
    data = edge_bo,
    ggplot2::aes(x = x1, y = y1, xend = x2, yend = y2, linewidth = cohit_n, colour = edge_balance_plot),
    curvature = 0.06, alpha = 0.76, lineend = "round"
  ) +
  ggplot2::geom_point(
    data = layout_free,
    ggplot2::aes(x = x, y = y, fill = group, size = node_support, shape = node_type),
    colour = "grey15", stroke = 0.55, alpha = 0.97
  ) +
  label_repel(
    data = layout_free |> dplyr::filter(node_type == "Biomarker/molecular concept"),
    mapping = ggplot2::aes(x = x, y = y, label = node_label),
    size = 2.9
  ) +
  label_repel(
    data = layout_free |> dplyr::filter(node_type == "Disease-state B bridge"),
    mapping = ggplot2::aes(x = x, y = y, label = node_label),
    size = 3.2, fontface = "bold"
  ) +
  label_repel(
    data = layout_free |> dplyr::filter(node_type == "Clinical outcome"),
    mapping = ggplot2::aes(x = x, y = y, label = node_label),
    size = 3.6, fontface = "bold"
  ) +
  ggplot2::scale_shape_manual(values = node_shapes, name = "Node type") +
  ggplot2::scale_fill_manual(
    values = node_fill_values,
    breaks = active_concept_groups,
    labels = active_concept_group_labels,
    drop = TRUE,
    name = "Concept group"
  ) +
  ggplot2::scale_size_area(max_size = 8.0, breaks = c(5, 10, 25, 50, 100), name = "Node support
(total articles)") +
  ggplot2::scale_linewidth(range = c(0.20, 2.85), breaks = c(1, 3, 5, 10, 20, 50), name = "Edge support
(co-mentioned articles)") +
  ggplot2::scale_colour_gradient2(
    low = "#2166AC", mid = "#BDBDBD", high = "#B2182B", midpoint = 0,
    limits = c(-1, 1), na.value = "grey68", name = "Signed-effect
balance"
  ) +
  ggplot2::guides(
    linewidth = ggplot2::guide_legend(
      order = 1,
      override.aes = list(colour = "grey35", alpha = 1, linetype = "solid")
    ),
    size = ggplot2::guide_legend(
      order = 2,
      override.aes = list(shape = 21, fill = "grey30", colour = "grey15", alpha = 1)
    ),
    fill = ggplot2::guide_legend(
      order = 3,
      ncol = 1,
      override.aes = list(
        shape = 21,
        size = 3.4,
        fill = active_concept_group_fills,
        colour = "grey18",
        alpha = 1
      )
    ),
    shape = ggplot2::guide_legend(
      order = 4,
      override.aes = list(size = 3.0, fill = "white", colour = "grey15", alpha = 1)
    ),
    colour = ggplot2::guide_colourbar(
      order = 5,
      barheight = grid::unit(2.3, "cm"),
      barwidth = grid::unit(0.35, "cm")
    )
  ) +
  ggplot2::coord_equal(clip = "off") +
  ggplot2::labs(
    title = "Figure 5. Biomarker–bridge–outcome signal atlas",
    subtitle = "Fully free data-driven layout; dotted grey edges show biomarker-to-B co-mentions; node distance summarises relative literature connectivity"
  ) +
  base_theme_void +
  ggplot2::theme(
    legend.position = "right",
    legend.justification = "center",
    legend.box.spacing = grid::unit(0.10, "cm")
  )

# Panel B as an algorithmic text-summary map, styled like a compact atlas panel.

# Supplementary full matrix
if (nrow(supp_matrix)) {
  pS <- ggplot2::ggplot(supp_matrix, ggplot2::aes(x = outcome_label, y = display_label_unique)) +
    ggplot2::geom_point(ggplot2::aes(size = cohit_n, fill = fill_value), shape = 21, colour = "grey35", stroke = 0.25, alpha = 0.95) +
    ggplot2::facet_grid(group ~ ., scales = "free_y", space = "free_y", switch = "y") +
    ggplot2::scale_size_area(max_size = 8, breaks = c(1, 5, 10, 20, 40, 60), name = "Co-mentioned\narticles") +
    ggplot2::scale_fill_gradient2(low = "#2166AC", mid = "#FFFFFF", high = "#B2182B", midpoint = 0, limits = c(-1, 1), na.value = "grey82", name = "Signed-effect\nbalance") +
    ggplot2::labs(
      title = "Supplementary Figure. Full biomarker / molecular signal matrix",
      subtitle = "Current dictionary biomarker/molecular scope; treatment, infection, measurement and disease-state bridge nodes excluded",
      x = "Clinical worsening outcome", y = NULL
    ) +
    ggplot2::theme_minimal(base_size = 9) +
    ggplot2::theme(
      plot.title = ggplot2::element_text(face = "bold", size = 13),
      plot.subtitle = ggplot2::element_text(size = 8.3),
      strip.text.y.left = ggplot2::element_text(angle = 0, face = "bold", size = 7.5),
      axis.text.y = ggplot2::element_text(size = 6.5),
      legend.title = ggplot2::element_text(size = 7.5),
      legend.text = ggplot2::element_text(size = 6.5),
      panel.grid.minor = ggplot2::element_blank()
    )
} else {
  pS <- ggplot2::ggplot() + ggplot2::annotate("text", x = 0, y = 0, label = "No supplementary biomarker/molecular signals after filtering") + ggplot2::theme_void()
}

# -------------------------

# -------------------------
# 11) Final Figure 5 output: free-layout network only
# -------------------------
fig_pdf <- file.path(DIR_FIG2, sprintf("Figure5_biomarker_molecular_free_atlas_FINAL_%s__%s.pdf", CORPUS_TAG, DIC_TAG))
fig_png <- file.path(DIR_FIG2, sprintf("Figure5_biomarker_molecular_free_atlas_FINAL_%s__%s.png", CORPUS_TAG, DIC_TAG))
fig_supp_pdf <- file.path(DIR_FIG2, sprintf("Supplementary_Figure5_full_biomarker_molecular_matrix_%s__%s.pdf", CORPUS_TAG, DIC_TAG))
fig_supp_png <- file.path(DIR_FIG2, sprintf("Supplementary_Figure5_full_biomarker_molecular_matrix_%s__%s.png", CORPUS_TAG, DIC_TAG))

pdf(fig_pdf, width = 11.2, height = 8.4, onefile = TRUE)
print(pA)
dev.off()

png(fig_png, width = round(11.2 * FIG_DPI), height = round(8.4 * FIG_DPI), res = FIG_DPI)
print(pA)
dev.off()

pdf(fig_supp_pdf, width = 9.2, height = 12.0, onefile = TRUE)
print(pS)
dev.off()

png(fig_supp_png, width = round(9.2 * FIG_DPI), height = round(12.0 * FIG_DPI), res = FIG_DPI)
print(pS)
dev.off()

# -------------------------
# 12) Selection rules and run summary
# -------------------------
selection_rules <- tibble::tibble(
  item = c(
    "biomarker_scope", "B_bridge_scope", "exclusions", "biomarker_node_selection",
    "B_node_selection", "edge_selection", "Figure5_layout",
    "edge_width", "edge_colour", "named_anchor_terms", "interpretation"
  ),
  rule = c(
    "Current dictionary metadata: serological, biomarker, cellular, molecular or pathway domains/subroles/families",
    "Current primary-atlas B nodes excluding biomarker/molecular, treatment, infection, context, measurement and outcome nodes",
    "Treatment, infection, comparator/context, measurement/modality and non-scope disease-state nodes are excluded from biomarker/molecular scope",
    "Top biomarker/molecular concepts by data-derived display_score using outcome co-mention, outcome sharedness, B-bridge co-mention and direction-bearing support",
    "Top disease-state B bridges by data-derived display_score using outcome co-mention, outcome sharedness and co-mention with selected biomarker/molecular concepts",
    "Edges are filtered by prespecified co-mention thresholds and maximum-edge caps; no edge is manually forced into display",
    "Fully free deterministic Fruchterman-Reingold layout using prespecified co-mention weights; no outcome, biomarker or B node is manually fixed or positioned",
    "Unique article-level co-mention count from hit matrix",
    "Signed-effect balance when available for term-outcome edges; grey for co-mention-only or undirected biomarker-B edges",
    "None. No named biomarker, B node or result-derived term is boosted or manually forced into display.",
    "Exploratory literature-derived signal atlas; not a causal diagram, validated biomarker panel or prediction model"
  )
)
write_csv2(selection_rules, file.path(DIR_TABLE, sprintf("Figure5_selection_rules_%s__%s.csv", CORPUS_TAG, DIC_TAG)))

run_summary <- tibble::tibble(
  run_name = RUN_NAME,
  corpus_tag = CORPUS_TAG,
  dictionary_tag = DIC_TAG,
  dictionary_file = DIC_FILE,
  n_biomarker_scope_terms = nrow(biomarker_scope),
  n_B_bridge_scope_terms = nrow(bridge_scope),
  n_selected_biomarker_terms = length(selected_biomarkers),
  n_selected_B_bridge_terms = length(selected_bridges),
  n_edges_total = nrow(edge_df),
  n_biomarker_outcome_edges = nrow(bio_outcome_edges),
  n_biomarker_B_edges = nrow(bio_bridge_edges),
  n_B_outcome_edges = nrow(bridge_outcome_edges),
  min_bio_outcome_cohit = MIN_BIO_OUTCOME_COHIT,
  min_bio_bridge_cohit = MIN_BIO_BRIDGE_COHIT,
  min_bridge_outcome_cohit = MIN_BRIDGE_OUTCOME_COHIT,
  max_biomarker_terms = MAX_BIOMARKER_TERMS,
  max_B_bridge_terms = MAX_B_BRIDGE_TERMS,
  output_pdf = fig_pdf,
  output_supp_pdf = fig_supp_pdf,
  interpretation = "Final data-driven Figure 5: fully free force-directed biomarker/molecular signal atlas overlaid on selected B bridge and outcome layers. Treatment, infection, measurement and non-scope disease-state nodes are excluded. No named anchors or manual term forcing are used."
)
write_csv2(run_summary, file.path(DIR_TABLE, sprintf("Figure5_run_summary_%s__%s.csv", CORPUS_TAG, DIC_TAG)))

log_msg("WROTE:", fig_pdf)
log_msg("WROTE:", fig_png)
log_msg("WROTE:", fig_supp_pdf)
log_msg("WROTE:", fig_supp_png)
log_msg("=== END ", RUN_NAME, " ===")
