# =========================================================
# 12_FigureTermProvenance_AtlasV2.R
# RA-ILD atlas v2.2.x manuscript support table builder
#
# Purpose
#   Build figure-level provenance tables for all concept nodes and edges that
#   appear in current manuscript Figures 2-6 and Supplementary Figure 5.
#
# Scientific role
#   This is a transparency/reproducibility table, not a new primary analysis.
#   It traces displayed terms back to:
#     - current dictionary metadata and analysis layers
#     - PMID-level hit-matrix support across AE-ILD, progression and mortality
#     - co-mention/NPMI/lift tables where available
#     - signed-effect summaries where available
#     - ABC bridge rankings/edges where applicable
#     - figure-specific source tables generated by scripts 07-11
#
# Data-driven transparency
#   The script does not add, force, anchor, boost or manually curate terms for
#   the provenance table. It harvests terms/edges already present in figure
#   source tables and joins support metrics by term/outcome.
#
# Required prior outputs
#   00_setup_AtlasV2.R
#   02_BuildHitsMatrix_AtlasV2.R output: hits_matrix_*.csv
#   Recommended: outputs from 03-11
#
# Main outputs
#   Supplementary_Table_Figure_Term_Provenance_LONG_*.csv
#   Supplementary_Table_Figure_Term_Provenance_SUMMARY_*.csv
#   Supplementary_Table_Figure_Edge_Provenance_*.csv
#   Supplementary_Table_Figure_Selection_Rules_*.csv
#   Supplementary_Table_Context_Layer_QC_*.csv
#   FigureTermProvenance_run_summary_*.csv
# =========================================================

source(file.path(getwd(), "00_setup_AtlasV2.R"))
assert_atlas_v2_setup(require_dictionary = TRUE)
quiet_install(c("dplyr", "readr", "stringr", "tibble", "tidyr", "purrr"))

RUN_NAME <- "12_FigureTermProvenance_AtlasV2"
log_msg("=== START ", RUN_NAME, " ===")

# -------------------------
# 0) Helpers
# -------------------------
if (!exists("write_csv2")) write_csv2 <- function(x, path) readr::write_csv(x, path)

safe_chr <- function(x) {
  x <- as.character(x)
  x[is.na(x)] <- ""
  x
}

safe_num <- function(x, default = NA_real_) {
  y <- suppressWarnings(as.numeric(x))
  ifelse(is.na(y), default, y)
}

safe_int <- function(x, default = 0L) {
  y <- suppressWarnings(as.integer(x))
  ifelse(is.na(y), default, y)
}

norm_term <- function(x) {
  x <- safe_chr(x)
  x <- stringr::str_trim(x)
  x <- gsub("^hit__", "", x)
  x <- gsub("^node__", "", x)
  x
}

file_base <- function(x) basename(as.character(x))

read_optional_table <- function(prefix) {
  exact <- file.path(DIR_TABLE, sprintf("%s_%s__%s.csv", prefix, CORPUS_TAG, DIC_TAG))
  if (file.exists(exact)) {
    log_msg("Loaded table:", exact)
    return(readr::read_csv(exact, show_col_types = FALSE))
  }
  regex <- sprintf("^%s_.*__%s\\.csv$", prefix, DIC_TAG)
  alt <- find_latest_file(DIR_TABLE, regex)
  if (!is.na(alt) && file.exists(alt)) {
    log_msg("Loaded latest matching table:", alt)
    return(readr::read_csv(alt, show_col_types = FALSE))
  }
  log_msg("Optional table not found; using empty table for prefix:", prefix)
  tibble::tibble()
}

read_optional_file <- function(filename_regex) {
  f <- find_latest_file(DIR_TABLE, filename_regex)
  if (!is.na(f) && file.exists(f)) {
    log_msg("Loaded latest matching file:", f)
    return(readr::read_csv(f, show_col_types = FALSE))
  }
  log_msg("Optional file not found; using empty table for regex:", filename_regex)
  tibble::tibble()
}

hit_col <- function(term) paste0("hit__", term)

get_vec <- function(df, term) {
  nm <- hit_col(term)
  if (!nm %in% names(df)) return(integer(nrow(df)))
  as.integer(ifelse(is.na(df[[nm]]), 0L, df[[nm]] > 0L))
}

cohit_count <- function(df, term1, term2) {
  x <- get_vec(df, term1)
  y <- get_vec(df, term2)
  as.integer(sum(x == 1L & y == 1L, na.rm = TRUE))
}

first_present_col <- function(df, candidates) {
  hit <- intersect(candidates, names(df))
  if (length(hit)) hit[1] else NA_character_
}

col_chr <- function(df, col, default = "") {
  if (!is.na(col) && col %in% names(df)) return(safe_chr(df[[col]]))
  rep(default, nrow(df))
}

col_num <- function(df, col, default = NA_real_) {
  if (!is.na(col) && col %in% names(df)) return(safe_num(df[[col]], default = default))
  rep(default, nrow(df))
}

col_int <- function(df, col, default = NA_integer_) {
  if (!is.na(col) && col %in% names(df)) return(safe_int(df[[col]], default = default))
  rep(default, nrow(df))
}

col_first_chr <- function(df, candidates, default = "") {
  col <- first_present_col(df, candidates)
  col_chr(df, col, default = default)
}

col_first_num <- function(df, candidates, default = NA_real_) {
  col <- first_present_col(df, candidates)
  col_num(df, col, default = default)
}

paste_nonempty <- function(x, sep = ";") {
  x <- unique(safe_chr(x))
  x <- x[nzchar(x)]
  if (!length(x)) "" else paste(x, collapse = sep)
}

collapse_max <- function(x) {
  x <- safe_num(x)
  if (all(is.na(x))) NA_real_ else max(x, na.rm = TRUE)
}

# Create a metric summary string from whatever common metric columns a source table has.
metric_blob <- function(df) {
  metric_cols <- intersect(
    c("n11", "cohit_n", "co_mentioned_articles", "unique_term_outcome_articles",
      "unique_domain_outcome_articles", "summed_term_outcome_cohits", "figure_size_metric",
      "articles", "signed_articles", "direction_articles", "total_articles", "total_support",
      "score_q", "support_hmean", "AB_n11", "BC_n11", "AC_n11", "npmi", "lift", "q",
      "balance", "direction_balance", "signed_balance", "weighted_direction_balance"),
    names(df)
  )
  if (!length(metric_cols)) return(rep("", nrow(df)))
  purrr::map_chr(seq_len(nrow(df)), function(i) {
    vals <- purrr::map_chr(metric_cols, function(m) {
      val <- df[[m]][i]
      if (length(val) == 0 || is.na(val)) return("")
      paste0(m, "=", as.character(signif(safe_num(val, default = val), 4)))
    })
    paste(vals[nzchar(vals)], collapse = "; ")
  })
}

# -------------------------
# 1) Load core inputs
# -------------------------
dic <- load_atlas_dictionary(require_dictionary = TRUE) |>
  dplyr::mutate(term = safe_chr(term))

hits <- load_hit_matrix()
terms_present <- hit_terms_present(hits, dic)
OUTCOMES <- PRIMARY_OUTCOME_TERMS
OUTCOME_LABELS <- c("AE-ILD" = "AE-ILD", "progression" = "Progression", "mortality" = "Mortality")

meta_cols <- c(
  "term", "concept_id", "preferred_label", "original_term", "original_class", "class", "regex",
  "abc_role", "abc_subrole", "domain", "concept_family", "node_level", "analysis_tier",
  "atlas_layer", "include_primary", "primary_atlas_eligible", "retain_reason", "notes"
)

dic_meta <- dic |>
  dplyr::select(dplyr::any_of(meta_cols)) |>
  dplyr::mutate(
    term = safe_chr(term),
    dictionary_hit_present = term %in% terms_present
  )

# -------------------------
# 2) Term coverage and term-outcome support from hit matrix
# -------------------------
coverage <- read_optional_table("dictionary_term_coverage")
if (nrow(coverage)) {
  cov_term_col <- first_present_col(coverage, c("term", "concept_id", "original_term"))
  if (!is.na(cov_term_col)) {
    coverage <- coverage |>
      dplyr::mutate(term = norm_term(.data[[cov_term_col]])) |>
      dplyr::select(dplyr::any_of(c("term", "corpus_hit_n", "corpus_hit_pct", "example_pmids", "examples", "hit_articles")))
  } else {
    coverage <- tibble::tibble(term = character())
  }
} else {
  coverage <- tibble::tibble(term = character())
}

# PMID-level term-outcome support for all dictionary terms.
term_outcome_support <- purrr::map_dfr(dic$term, function(t) {
  purrr::map_dfr(OUTCOMES, function(o) {
    tibble::tibble(
      term = t,
      outcome = o,
      term_outcome_cohit_articles = cohit_count(hits, t, o)
    )
  })
})

term_support_summary <- term_outcome_support |>
  dplyr::group_by(term) |>
  dplyr::summarise(
    outcomes_supported = sum(term_outcome_cohit_articles > 0, na.rm = TRUE),
    outcome_support_vector = paste(paste0(outcome, "=", term_outcome_cohit_articles), collapse = "; "),
    total_outcome_cohit_articles = sum(term_outcome_cohit_articles, na.rm = TRUE),
    max_outcome_cohit_articles = max(term_outcome_cohit_articles, na.rm = TRUE),
    dominant_outcome = ifelse(max_outcome_cohit_articles > 0, outcome[which.max(term_outcome_cohit_articles)], NA_character_),
    .groups = "drop"
  )

# -------------------------
# 3) Coherence and signed-effect support
# -------------------------
cooc_all <- dplyr::bind_rows(
  read_optional_table("cooc_npmi_lift_all_layers"),
  read_optional_table("cooc_npmi_lift_scoped_layers"),
  read_optional_table("cooc_npmi_lift_primary_atlas"),
  read_optional_table("cooc_npmi_lift_treatment_context"),
  read_optional_table("cooc_npmi_lift_infection_context")
) |>
  dplyr::distinct()

if (nrow(cooc_all)) {
  cooc_term_col <- first_present_col(cooc_all, c("A", "term", "from"))
  cooc_outcome_col <- first_present_col(cooc_all, c("C", "outcome", "to"))
  cooc_support <- cooc_all |>
    dplyr::transmute(
      term = norm_term(cooc_all[[cooc_term_col]]),
      outcome = norm_term(cooc_all[[cooc_outcome_col]]),
      cooc_scope = col_chr(cooc_all, "scope", ""),
      n11 = col_int(cooc_all, "n11", NA_integer_),
      npmi = col_num(cooc_all, "npmi", NA_real_),
      lift = col_num(cooc_all, "lift", NA_real_),
      q = col_num(cooc_all, "q", NA_real_)
    ) |>
    dplyr::filter(term != "", outcome %in% OUTCOMES) |>
    dplyr::group_by(term, outcome) |>
    dplyr::summarise(
      cooc_scopes = paste_nonempty(cooc_scope),
      n11 = collapse_max(n11),
      npmi = collapse_max(npmi),
      lift = collapse_max(lift),
      q = suppressWarnings(min(q, na.rm = TRUE)),
      .groups = "drop"
    ) |>
    dplyr::mutate(q = ifelse(is.infinite(q), NA_real_, q))
} else {
  cooc_support <- tibble::tibble(term = character(), outcome = character())
}

signed_all <- read_optional_table("signed_effects_summary_withCI")
if (nrow(signed_all)) {
  signed_term_col <- first_present_col(signed_all, c("A", "term"))
  signed_outcome_col <- first_present_col(signed_all, c("C", "outcome"))
  signed_support <- signed_all |>
    dplyr::transmute(
      term = norm_term(signed_all[[signed_term_col]]),
      outcome = norm_term(signed_all[[signed_outcome_col]]),
      signed_analysis_scope = col_chr(signed_all, "analysis_scope", ""),
      signed_articles = col_int(signed_all, "articles", NA_integer_),
      pos_articles = col_int(signed_all, "pos_articles", NA_integer_),
      neg_articles = col_int(signed_all, "neg_articles", NA_integer_),
      mixed_articles = col_int(signed_all, "mixed_articles", NA_integer_),
      signed_balance = col_num(signed_all, "balance", NA_real_),
      balance_low = col_num(signed_all, "balance_low", NA_real_),
      balance_high = col_num(signed_all, "balance_high", NA_real_)
    ) |>
    dplyr::filter(term != "", outcome %in% OUTCOMES) |>
    dplyr::group_by(term, outcome) |>
    dplyr::summarise(
      signed_scopes = paste_nonempty(signed_analysis_scope),
      signed_articles = collapse_max(signed_articles),
      pos_articles = collapse_max(pos_articles),
      neg_articles = collapse_max(neg_articles),
      mixed_articles = collapse_max(mixed_articles),
      signed_balance = signed_balance[which.max(dplyr::if_else(is.na(signed_articles), -Inf, signed_articles))][1],
      balance_low = balance_low[which.max(dplyr::if_else(is.na(signed_articles), -Inf, signed_articles))][1],
      balance_high = balance_high[which.max(dplyr::if_else(is.na(signed_articles), -Inf, signed_articles))][1],
      .groups = "drop"
    )
} else {
  signed_support <- tibble::tibble(term = character(), outcome = character())
}

# -------------------------
# 4) Harvest terms from figure source tables
# -------------------------
make_event_rows <- function(df, source_file, figure, panel, figure_role, term_cols,
                            outcome_cols = c("outcome", "C", "clinical_outcome"),
                            selection_rule = "", supplementary = FALSE) {
  if (!nrow(df)) return(tibble::tibble())
  tcols <- intersect(term_cols, names(df))
  if (!length(tcols)) return(tibble::tibble())
  ocol <- first_present_col(df, outcome_cols)
  metric <- metric_blob(df)
  purrr::map_dfr(tcols, function(tc) {
    tibble::tibble(
      figure = figure,
      panel = panel,
      supplementary = supplementary,
      figure_role = figure_role,
      term = norm_term(df[[tc]]),
      source_column = tc,
      source_file = file_base(source_file),
      source_row = seq_len(nrow(df)),
      outcome = if (!is.na(ocol)) norm_term(df[[ocol]]) else "",
      selection_rule = selection_rule,
      source_metric_blob = metric
    )
  }) |>
    dplyr::filter(term != "", !is.na(term)) |>
    dplyr::distinct()
}

read_source <- function(prefix, regex = NULL) {
  if (!is.null(regex)) {
    f <- find_latest_file(DIR_TABLE, regex)
  } else {
    f <- find_latest_file(DIR_TABLE, sprintf("^%s_.*__%s\\.csv$", prefix, DIC_TAG))
  }
  if (is.na(f) || !file.exists(f)) return(list(path = NA_character_, data = tibble::tibble()))
  list(path = f, data = readr::read_csv(f, show_col_types = FALSE))
}

source_specs <- list(
  list(prefix = "outcome_domain_matrix_top_terms", fig = "Figure 2", panel = "Outcome-domain matrix", role = "cell top concept node", term_cols = c("term", "A"), rule = "Outcome-domain top nodes selected by term-outcome article support within prespecified clinical-domain cells."),
  list(prefix = "outcome_domain_matrix_main_pairs", fig = "Figure 2", panel = "Outcome-domain matrix", role = "term-outcome pair", term_cols = c("term", "A"), rule = "Outcome-domain pair evidence from current dictionary and hit matrix."),
  list(prefix = "Figure2_outcome_domain_atlas_DISPLAY_TABLE", fig = "Figure 2", panel = "Outcome-domain matrix", role = "domain-level display cell", term_cols = c("top_term", "term", "A"), rule = "Domain-level display values generated algorithmically from outcome-domain evidence."),

  list(prefix = "Figure3_AEILD_signed_top_terms", fig = "Figure 3", panel = "A", role = "AE-ILD signed wording term", term_cols = c("term", "A"), rule = "AE-ILD signed-effect terms selected by direction-bearing support and display limits."),
  list(prefix = "Figure3_AEILD_bridge_triads_FINAL", fig = "Figure 3", panel = "B", role = "AE-ILD ABC triad component", term_cols = c("A", "B", "C"), rule = "Conservative AE-ILD ABC triads from primary disease-state atlas with prespecified support filters."),
  list(prefix = "Figure3_AEILD_bridge_evidence_AEILD_only", fig = "Figure 3", panel = "C", role = "AE-ILD-only evidence term", term_cols = c("term", "B", "A", "C"), rule = "AE-ILD-only bridge evidence combining ABC, co-mention and signed wording support."),
  list(prefix = "Figure3_AEILD_bridge_nodes", fig = "Figure 3", panel = "B/C", role = "AE-ILD bridge network node", term_cols = c("term", "node_id", "id", "name"), rule = "Displayed nodes in AE-ILD bridge atlas."),
  list(prefix = "Figure3_AEILD_bridge_edges", fig = "Figure 3", panel = "B/C", role = "AE-ILD bridge network edge endpoint", term_cols = c("from", "to"), rule = "Displayed edge endpoints in AE-ILD bridge atlas."),

  list(prefix = "Figure4_PM_bridge_triads_display", fig = "Figure 4", panel = "A/B", role = "progression/mortality ABC triad component", term_cols = c("A", "B", "C"), rule = "Progression and mortality ABC triads selected by primary disease-state atlas support filters."),
  list(prefix = "Figure4_PM_bridge_panelC_display", fig = "Figure 4", panel = "C", role = "shared/outcome-facing bridge term", term_cols = c("term", "B", "A"), rule = "Shared and outcome-facing bridge concepts assigned algorithmically from progression/mortality bridge evidence."),
  list(prefix = "Figure4_PM_bridge_shared_outcome_facing_summary", fig = "Figure 4", panel = "C", role = "shared/outcome-facing bridge summary term", term_cols = c("term", "B", "A"), rule = "Summary of shared and outcome-facing progression/mortality bridge concepts."),
  list(prefix = "Figure4_PM_bridge_nodes", fig = "Figure 4", panel = "A/B", role = "progression/mortality bridge network node", term_cols = c("term", "node_id", "id", "name"), rule = "Displayed nodes in progression/mortality bridge atlas."),
  list(prefix = "Figure4_PM_bridge_edges", fig = "Figure 4", panel = "A/B", role = "progression/mortality bridge network edge endpoint", term_cols = c("from", "to"), rule = "Displayed edge endpoints in progression/mortality bridge atlas."),

  list(prefix = "Figure5_free_nodes", fig = "Figure 5", panel = "Main", role = "free-layout network node", term_cols = c("term", "node_id", "id", "name"), rule = "Biomarker/molecular free-layout network nodes selected from dictionary scope and article-level support metrics."),
  list(prefix = "Figure5_free_edges", fig = "Figure 5", panel = "Main", role = "free-layout network edge endpoint", term_cols = c("from", "to"), rule = "Biomarker-outcome, biomarker-bridge and bridge-outcome network edge endpoints selected by article-level co-mention thresholds."),
  list(prefix = "Figure5_biomarker_molecular_summary", fig = "Figure 5", panel = "Main", role = "biomarker/molecular term summary", term_cols = c("term"), rule = "Biomarker/molecular term support summary from current dictionary scope."),
  list(prefix = "Figure5_B_bridge_summary", fig = "Figure 5", panel = "Main", role = "B bridge term summary", term_cols = c("term"), rule = "Selected disease-state B bridge support summary used in biomarker/molecular network."),
  list(prefix = "Supplementary_Figure5_full_biomarker_molecular_matrix_data", fig = "Supplementary Figure S3", panel = "Full biomarker/molecular matrix", role = "supplementary matrix term", term_cols = c("term"), rule = "Full biomarker/molecular outcome matrix for current dictionary scope.", supp = TRUE),

  list(prefix = "Figure6_integrated_signal_display_TERMS", fig = "Figure 6", panel = "Integrated summary", role = "displayed shared/outcome-facing term", term_cols = c("term"), rule = "Integrated summary terms assigned by all-three-outcome sharedness, two-outcome dagger rule and outcome-facing support."),
  list(prefix = "Figure6_integrated_signal_assignments_ALL", fig = "Figure 6", panel = "Integrated summary", role = "assigned integrated summary term", term_cols = c("term"), rule = "All terms assigned to shared/outcome-facing categories by data-driven rules."),
  list(prefix = "Figure6_integrated_term_outcome_evidence_ALL", fig = "Figure 6", panel = "Integrated summary", role = "integrated term-outcome evidence", term_cols = c("term"), rule = "Term-outcome evidence underlying integrated Figure 6 summary.")
)

figure_events <- purrr::map_dfr(source_specs, function(sp) {
  src <- read_source(sp$prefix)
  if (!nrow(src$data)) return(tibble::tibble())
  make_event_rows(
    src$data, src$path, sp$fig, sp$panel, sp$role,
    term_cols = sp$term_cols,
    selection_rule = sp$rule,
    supplementary = isTRUE(sp$supp)
  )
})

# Keep outcome terms in provenance but flag them as outcome nodes.
if (!nrow(figure_events)) {
  warning("No figure source tables were found. Run 07-11 before running provenance table builder.")
  figure_events <- tibble::tibble(
    figure = character(), panel = character(), supplementary = logical(), figure_role = character(), term = character(),
    source_column = character(), source_file = character(), source_row = integer(), outcome = character(),
    selection_rule = character(), source_metric_blob = character()
  )
}

# -------------------------
# 5) Add ABC edge/triad provenance as an edge table
# -------------------------
triad_sources <- list(
  list(prefix = "abc_rankings_primary_AEILD_main_filtered", figure = "Figure 3", panel = "B", context = "AE-ILD conservative ABC"),
  list(prefix = "Figure3_AEILD_bridge_triads_FINAL", figure = "Figure 3", panel = "B", context = "AE-ILD bridge atlas display"),
  list(prefix = "Figure4_PM_bridge_triads_display", figure = "Figure 4", panel = "A/B", context = "Progression/mortality bridge atlas display"),
  list(prefix = "abc_rankings_primary_main_filtered", figure = "Core ABC", panel = "all outcomes", context = "All primary main-filtered triads")
)

triad_prov <- purrr::map_dfr(triad_sources, function(sp) {
  src <- read_source(sp$prefix)
  if (!nrow(src$data)) return(tibble::tibble())
  df <- src$data
  if (!all(c("A", "B", "C") %in% names(df))) return(tibble::tibble())
  df |>
    dplyr::transmute(
      figure = sp$figure,
      panel = sp$panel,
      source_file = file_base(src$path),
      source_row = dplyr::row_number(),
      edge_context = sp$context,
      A = norm_term(A), B = norm_term(B), C = norm_term(C),
      AB_n11 = col_int(df, "AB_n11", NA_integer_),
      BC_n11 = col_int(df, "BC_n11", NA_integer_),
      AC_n11 = col_int(df, "AC_n11", NA_integer_),
      AB_npmi = col_num(df, "AB_npmi", NA_real_),
      BC_npmi = col_num(df, "BC_npmi", NA_real_),
      score_q = col_num(df, "score_q", NA_real_),
      support_hmean = col_num(df, "support_hmean", NA_real_),
      selection_rule = "Primary disease-state ABC triad retained by current dictionary policy and prespecified AB/BC support filters."
    ) |>
    dplyr::distinct()
})

# Edge endpoints for network figures.
edge_sources <- list(
  list(prefix = "Figure3_AEILD_bridge_edges", figure = "Figure 3", panel = "B/C"),
  list(prefix = "Figure4_PM_bridge_edges", figure = "Figure 4", panel = "A/B"),
  list(prefix = "Figure5_free_edges", figure = "Figure 5", panel = "Main")
)
edge_prov <- purrr::map_dfr(edge_sources, function(sp) {
  src <- read_source(sp$prefix)
  if (!nrow(src$data)) return(tibble::tibble())
  df <- src$data
  if (!all(c("from", "to") %in% names(df))) return(tibble::tibble())
  df |>
    dplyr::transmute(
      figure = sp$figure,
      panel = sp$panel,
      source_file = file_base(src$path),
      source_row = dplyr::row_number(),
      from = norm_term(from),
      to = norm_term(to),
      edge_type = col_first_chr(df, c("edge_type", "kind"), ""),
      edge_support = col_first_num(df, c("cohit_n", "w", "weight", "edge_support"), NA_real_),
      signed_balance = col_first_num(df, c("signed_balance", "balance", "direction_balance"), NA_real_),
      selection_rule = "Displayed network edge retained by figure-specific data-driven support thresholds."
    ) |>
    dplyr::filter(from != "", to != "") |>
    dplyr::distinct()
})

# -------------------------
# 6) Merge provenance with dictionary and support metrics
# -------------------------
term_outcome_support_wide <- term_outcome_support |>
  dplyr::mutate(outcome_col = paste0("cohit_", make.names(outcome))) |>
  dplyr::select(term, outcome_col, term_outcome_cohit_articles) |>
  tidyr::pivot_wider(names_from = outcome_col, values_from = term_outcome_cohit_articles, values_fill = 0)

prov_long <- figure_events |>
  dplyr::left_join(dic_meta, by = "term") |>
  dplyr::left_join(coverage, by = "term") |>
  dplyr::left_join(term_support_summary, by = "term") |>
  dplyr::left_join(term_outcome_support, by = c("term", "outcome")) |>
  dplyr::left_join(cooc_support, by = c("term", "outcome")) |>
  dplyr::left_join(signed_support, by = c("term", "outcome")) |>
  dplyr::mutate(
    outcome_label = dplyr::recode(outcome, !!!OUTCOME_LABELS, .default = outcome),
    is_primary_outcome_node = term %in% OUTCOMES,
    is_displayed_in_main_figure = !supplementary,
    provenance_note = dplyr::case_when(
      is_primary_outcome_node ~ "Clinical outcome node; used as target outcome, not interpreted as an upstream signal.",
      atlas_layer == "treatment_context" ~ "Treatment-context node; retained separately, not interpreted as treatment effect or drug-risk estimate.",
      atlas_layer == "infection_context" ~ "Infection-context node; retained separately, not interpreted as causal infection attribution.",
      abc_subrole %in% c("B_measurement_modality", "B_measurement_derived_imaging_feature") ~ "Measurement/modality node; retained outside primary disease-state bridge claims.",
      TRUE ~ "Displayed according to current dictionary metadata and figure-specific support rules."
    )
  ) |>
  dplyr::relocate(figure, panel, figure_role, term, preferred_label, outcome, outcome_label, source_file, source_row)

# A compact one-row-per-term summary across all figures.
prov_summary <- prov_long |>
  dplyr::group_by(term) |>
  dplyr::summarise(
    preferred_label = dplyr::first(preferred_label[!is.na(preferred_label)]),
    figures = paste_nonempty(figure),
    panels = paste_nonempty(paste(figure, panel, sep = ":")),
    figure_roles = paste_nonempty(figure_role),
    main_or_supplementary = dplyr::case_when(
      any(!supplementary, na.rm = TRUE) & any(supplementary, na.rm = TRUE) ~ "main + supplementary",
      any(!supplementary, na.rm = TRUE) ~ "main",
      TRUE ~ "supplementary"
    ),
    abc_role = dplyr::first(abc_role),
    abc_subrole = dplyr::first(abc_subrole),
    domain = dplyr::first(domain),
    concept_family = dplyr::first(concept_family),
    node_level = dplyr::first(node_level),
    atlas_layer = dplyr::first(atlas_layer),
    analysis_tier = dplyr::first(analysis_tier),
    include_primary = dplyr::first(include_primary),
    dictionary_hit_present = dplyr::first(dictionary_hit_present),
    corpus_hit_n = dplyr::first(corpus_hit_n),
    corpus_hit_pct = dplyr::first(corpus_hit_pct),
    outcomes_supported = dplyr::first(outcomes_supported),
    outcome_support_vector = dplyr::first(outcome_support_vector),
    total_outcome_cohit_articles = dplyr::first(total_outcome_cohit_articles),
    max_outcome_cohit_articles = dplyr::first(max_outcome_cohit_articles),
    dominant_outcome = dplyr::first(dominant_outcome),
    selection_rules = paste_nonempty(selection_rule),
    provenance_notes = paste_nonempty(provenance_note),
    .groups = "drop"
  ) |>
  dplyr::left_join(term_outcome_support_wide, by = "term") |>
  dplyr::arrange(dplyr::desc(main_or_supplementary == "main"), figure_roles, dplyr::desc(total_outcome_cohit_articles), term)

# Context-layer QC for treatment/infection/measurement separation.
context_qc <- dic_meta |>
  dplyr::left_join(coverage, by = "term") |>
  dplyr::left_join(term_support_summary, by = "term") |>
  dplyr::filter(
    atlas_layer %in% c("treatment_context", "infection_context", "sensitivity", "context_only") |
      abc_subrole %in% c("B_measurement_modality", "B_measurement_derived_imaging_feature") |
      domain %in% c("imaging_modality", "measurement_derived_imaging_feature")
  ) |>
  dplyr::mutate(
    separation_reason = dplyr::case_when(
      atlas_layer == "treatment_context" ~ "Treatment context separated from primary disease-state bridge claims.",
      atlas_layer == "infection_context" ~ "Infection context separated because trigger, complication, differential diagnosis and safety/outcome roles can overlap.",
      abc_subrole %in% c("B_measurement_modality", "B_measurement_derived_imaging_feature") | domain %in% c("imaging_modality", "measurement_derived_imaging_feature") ~ "Measurement/modality node retained as sensitivity/supporting layer rather than primary disease-state bridge.",
      atlas_layer == "context_only" ~ "Comparator or literature-context node not interpreted as RA-ILD worsening factor.",
      atlas_layer == "sensitivity" ~ "Sensitivity/supporting node retained outside primary display rules.",
      TRUE ~ "Supporting/context layer."
    )
  ) |>
  dplyr::arrange(atlas_layer, abc_subrole, term)

selection_rules <- tibble::tibble(
  figure = c("Figure 1", "Figure 2", "Figure 3", "Supplementary Figure S1", "Figure 4", "Supplementary Figure S2", "Figure 5", "Supplementary Figure S3", "Figure 6"),
  provenance_scope = c(
    "Dictionary and corpus-level summary; no individual term display provenance except dictionary node counts.",
    "Outcome-domain cell terms and layers.",
    "AE-ILD signed terms, ABC bridge triads and AE-ILD-only evidence layers.",
    "Treatment and infection context signals for AE-ILD.",
    "Progression/mortality ABC bridge maps and shared/outcome-facing bridge summary.",
    "Expanded ranked progression/mortality bridge triads.",
    "Biomarker/molecular free-layout network nodes and edges.",
    "Full biomarker/molecular outcome matrix.",
    "Integrated shared and outcome-facing clinical/bridge and biomarker/molecular summary."
  ),
  selection_rule = c(
    "Concept-node counts and coverage derived from current dictionary and hit matrix.",
    "Terms selected within prespecified outcome-domain cells by article-level support and direction-bearing evidence; treatment and infection retained as separate context rows.",
    "AE-ILD terms selected from primary atlas signed-effect, ABC and co-mention outputs with current dictionary policy; treatment/infection/measurement nodes excluded from primary bridge claims.",
    "Treatment and infection terms selected only from context layers and not interpreted as drug effects or causal infection attribution.",
    "Progression/mortality bridge triads selected from primary A/B/C terms using prespecified support filters; shared/outcome-facing summary generated algorithmically.",
    "Expanded triad ranking shown for transparency; x-axis may be log-scaled for readability; rankings are unchanged.",
    "Biomarker/molecular nodes selected from dictionary-defined scope and article-level support; B bridge/outcome nodes included to display network connectivity; no anchor-term boost or manual forcing.",
    "All biomarker/molecular term-outcome pairs in current scope with support are retained for supplementary display.",
    "Shared terms require support in all three outcomes; exactly two-outcome terms are marked with dagger and shown in corresponding outcome-facing boxes; outcome-adjacent descriptors are marked separately."
  ),
  manual_term_addition = "No displayed term was manually added after inspecting the figure; display is governed by dictionary metadata and support rules."
)

# -------------------------
# 7) Save outputs
# -------------------------
f_long <- file.path(DIR_TABLE, sprintf("Supplementary_Table_Figure_Term_Provenance_LONG_%s__%s.csv", CORPUS_TAG, DIC_TAG))
f_summary <- file.path(DIR_TABLE, sprintf("Supplementary_Table_Figure_Term_Provenance_SUMMARY_%s__%s.csv", CORPUS_TAG, DIC_TAG))
f_edges <- file.path(DIR_TABLE, sprintf("Supplementary_Table_Figure_Edge_Provenance_%s__%s.csv", CORPUS_TAG, DIC_TAG))
f_triads <- file.path(DIR_TABLE, sprintf("Supplementary_Table_Figure_Triad_Provenance_%s__%s.csv", CORPUS_TAG, DIC_TAG))
f_rules <- file.path(DIR_TABLE, sprintf("Supplementary_Table_Figure_Selection_Rules_%s__%s.csv", CORPUS_TAG, DIC_TAG))
f_ctx <- file.path(DIR_TABLE, sprintf("Supplementary_Table_Context_Layer_QC_%s__%s.csv", CORPUS_TAG, DIC_TAG))
f_run <- file.path(DIR_TABLE, sprintf("FigureTermProvenance_run_summary_%s__%s.csv", CORPUS_TAG, DIC_TAG))

write_csv2(prov_long, f_long)
write_csv2(prov_summary, f_summary)
write_csv2(edge_prov, f_edges)
write_csv2(triad_prov, f_triads)
write_csv2(selection_rules, f_rules)
write_csv2(context_qc, f_ctx)

run_summary <- tibble::tibble(
  corpus_tag = CORPUS_TAG,
  dic_tag = DIC_TAG,
  n_dictionary_terms = nrow(dic),
  n_terms_present_in_hit_matrix = length(terms_present),
  n_provenance_event_rows = nrow(prov_long),
  n_unique_terms_in_figures = dplyr::n_distinct(prov_long$term),
  n_unique_terms_in_main_figures = dplyr::n_distinct(prov_long$term[!prov_long$supplementary]),
  n_edge_rows = nrow(edge_prov),
  n_triad_rows = nrow(triad_prov),
  n_context_qc_rows = nrow(context_qc),
  outputs = paste(file_base(c(f_long, f_summary, f_edges, f_triads, f_rules, f_ctx)), collapse = "; "),
  interpretation = "Provenance tables trace displayed terms/edges to dictionary metadata and article-level support metrics. They do not create new primary results."
)
write_csv2(run_summary, f_run)

log_msg("WROTE:", f_long)
log_msg("WROTE:", f_summary)
log_msg("WROTE:", f_edges)
log_msg("WROTE:", f_triads)
log_msg("WROTE:", f_rules)
log_msg("WROTE:", f_ctx)
log_msg("=== DONE ", RUN_NAME, " ===")
